
[general]
	#Show empty armor icons?
	"Show empty icons" = false
	#Colors must be specified in #RRGGBB format
	"color values" = ["#FFFFFF", "#FF7F00", "#FFbF3F", "#2FFFEF", "#00FF00", "#7F00FF"]
	#Always show armor bar even if empty?
	"Always show bar" = false

