val air = <item:minecraft:air>;
<recipetype:botania:mana_infusion>.addJSONRecipe("agricarnation_infuse", {input: <item:botania:agricarnation>, output: <item:botania:agricarnation_chibi>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("andesite_infuse", {input: <item:minecraft:andesite>, output: <item:quark:jasper>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("bellethorn_infuse", {input: <item:botania:bellethorn>, output: <item:botania:bellethorn_chibi>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("bottle_infuse", {input: <item:minecraft:glass_bottle>, output: <item:botania:mana_bottle>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("bubbell_infuse", {input: <item:botania:bubbell>, output: <item:botania:bubbell_chibi>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("cookie_infuse", {input: <item:minecraft:cookie>, output: <item:botania:mana_cookie>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("diamond_infuse", {input: <item:minecraft:diamond>, output: <item:botania:mana_diamond>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("diorite_infuse", {input: <item:minecraft:diorite>, output: <item:minecraft:andesite>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("glass_infuse", {input: <tag:items:forge:glass>, output: <item:botania:mana_glass>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("granite_infuse", {input: <item:minecraft:granite>, output: <item:minecraft:diorite>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("grass_infuse", {input: <item:minecraft:grass>, output: <item:botania:grass_seeds>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("hopperhock_infuse", {input: <item:botania:hopperhock>, output: <item:botania:hopperhock_chibi>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("hydroangeas_infuse", {input: <item:botania:hydroangeas>, output: <item:botania:hydroangeas_motif>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("jasper_infuse", {input: <item:quark:jasper>, output: <item:quark:slate>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("limestone_infuse", {input: <item:quark:limestone>, output: <item:quark:marble>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("marble_infuse", {input: <item:quark:marble>, output: <item:minecraft:diorite>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("marimorphosis_infuse", {input: <item:botania:marimorphosis>, output: <item:botania:marimorphosis_chibi>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("pearl_infuse", {input: <item:minecraft:ender_pearl>, output: <item:botania:mana_pearl>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("piston_infuse", {input: <item:minecraft:piston>, output: <item:botania:piston_relay>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("poisonous_potato_infuse", {input: <item:minecraft:poisonous_potato>, output: <item:minecraft:potato>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("potato_infuse", {input: <item:minecraft:potato>, output: <item:botania:tiny_potato>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("quartz_infuse", {input: <item:minecraft:quartz>, output: <item:botania:mana_quartz>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("rannuncarpus_infuse", {input: <item:botania:rannuncarpus>, output: <item:botania:rannuncarpus_chibi>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("slate_infuse", {input: <item:quark:slate>, output: <item:quark:limestone>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("solegnolia_infuse", {input: <item:botania:solegnolia>, output: <item:botania:solegnolia_chibi>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("steel_infuse", {input: <item:mekanism:ingot_steel>, output: <item:botania:manasteel_ingot>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("string_infuse", {input: <item:minecraft:string>, output: <item:botania:mana_string>, mana: 100});
<recipetype:botania:mana_infusion>.addJSONRecipe("sugar_infuse", {input: <item:minecraft:sugar>, output: <item:botania:mana_powder>, mana: 100});
bigCompressWithUndo("dragonstone_block", <item:botania:dragonstone>, <item:botania:dragonstone_block>);
bigCompressWithUndo("elementium_block", <item:botania:elementium_ingot>, <item:botania:elementium_block>);
bigCompressWithUndo("elementium_nugget", <item:botania:elementium_nugget>, <item:botania:elementium_ingot>);
bigCompressWithUndo("ender_eye_block", <item:minecraft:ender_eye>, <item:botania:ender_eye_block>);
bigCompressWithUndo("mana_diamond_block", <item:botania:mana_diamond>, <item:botania:mana_diamond_block>);
bigCompressWithUndo("manasteel_block", <item:botania:manasteel_ingot>, <item:botania:manasteel_block>);
bigCompressWithUndo("manasteel_nugget", <item:botania:manasteel_nugget>, <item:botania:manasteel_ingot>);
bigCompressWithUndo("terrasteel_block", <item:botania:terrasteel_ingot>, <item:botania:terrasteel_block>);
bigCompressWithUndo("terrasteel_nugget", <item:botania:terrasteel_nugget>, <item:botania:terrasteel_ingot>);
bigCompressWithUndo("vine_ball", <item:minecraft:vine>, <item:botania:vine_ball>);
dye1("alfheim_portal", <item:botania:livingwood>, <item:botania:terrasteel_ingot>, <item:botania:alfheim_portal>);
dye1("apothecary_desert", <item:botania:metamorphic_desert_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_desert>);
dye1("apothecary_forest", <item:botania:metamorphic_forest_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_forest>);
dye1("apothecary_fungal", <item:botania:metamorphic_fungal_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_fungal>);
dye1("apothecary_mesa", <item:botania:metamorphic_mesa_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_mesa>);
dye1("apothecary_mountain", <item:botania:metamorphic_mountain_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_mountain>);
dye1("apothecary_plains", <item:botania:metamorphic_plains_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_plains>);
dye1("apothecary_swamp", <item:botania:metamorphic_swamp_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_swamp>);
dye1("apothecary_taiga", <item:botania:metamorphic_taiga_cobblestone>, <item:botania:apothecary_default>, <item:botania:apothecary_taiga>);
dye1("bellows", <item:botania:livingwood>, <item:minecraft:leather>, <item:botania:bellows>);
dye1("cocoon", <item:botania:mana_string>, <item:botania:fel_pumpkin>, <item:botania:cocoon>);
dye1("elementium_ingot", <item:mysticalagriculture:elementium_essence>, air, <item:botania:elementium_ingot> * 2);
dye1("mana_pool", <item:botania:livingrock>, <item:botania:mana_pearl>, <item:botania:mana_tablet>);
dye1("manasteel_ingot", <item:mysticalagriculture:manasteel_essence>, air, <item:botania:manasteel_ingot>);
dye1("pattern_donut", <item:botania:placeholder>, <item:minecraft:redstone>, <item:botania:pattern_donut>);
dye1("terrasteel", <item:mysticalagriculture:terrasteel_essence>, air, <item:botania:terrasteel_ingot>);
dye1("thorn_chakram", <item:minecraft:vine>, <item:botania:terrasteel_ingot>, <item:botania:thorn_chakram>);
dye1("tiny_planet_block", <item:botania:livingrock>, <item:botania:tiny_planet>, <item:botania:tiny_planet_block>);
dye1("turntable", <item:botania:livingwood>, <item:minecraft:sticky_piston>, <item:botania:turntable>);
dye8("quartz_blaze", <item:minecraft:quartz>, <item:minecraft:blaze_powder>, <item:botania:quartz_blaze>);
dye8("quartz_dark", <item:minecraft:quartz>, <tag:items:minecraft:coals>, <item:botania:quartz_dark>);
dye8("quartz_lavender", <item:minecraft:quartz>, <item:minecraft:pink_dye>, <item:botania:quartz_lavender>);
dye8("quartz_red", <item:minecraft:quartz>, <item:minecraft:rose_bush>, <item:botania:quartz_red>);
dye8("quartz_sunny", <item:minecraft:quartz>, <item:minecraft:sunflower>, <item:botania:quartz_sunny>);
dye8("temperance_stone", <item:minecraft:stone>, <item:botania:rune_earth>, <item:botania:temperance_stone>);
legs("dreamwood", <item:botania:dreamwood>, <item:botania:crafty_crate>);
legs("livingwood", <item:botania:livingwood>, <item:botania:open_crate>);
pickaxe("dragonstone", <item:botania:dragonstone>, <item:botania:missile_rod>, <item:botania:dreamwood_twig>);
shaped("abstruse_platform", <item:botania:abstruse_platform>, [[<item:botania:livingwood>, <item:botania:livingwood>, <item:botania:livingwood>], [<item:botania:livingwood>, <item:botania:mana_pearl>, <item:botania:livingwood>]]);
shaped("apothecary", <item:botania:apothecary_default>, [[<item:minecraft:cobblestone_slab>, <tag:items:botania:petals>, <item:minecraft:cobblestone_slab>], [air, <item:minecraft:cobblestone_slab>, air], [<item:minecraft:cobblestone_slab>, <item:minecraft:cobblestone_slab>, <item:minecraft:cobblestone_slab>]]);
shaped("astrolabe", <item:botania:astrolabe>, [[<item:botania:elementium_ingot>, <item:botania:dreamwood_twig>, <item:botania:sextant>], [<item:botania:elementium_ingot>, <item:botania:dreamwood_twig>, <item:botania:dreamwood_twig>], [<item:botania:elementium_ingot>, <item:botania:elementium_ingot>, <item:botania:elementium_ingot>]]);
shaped("avatar", <item:botania:avatar>, [[air, <item:botania:livingwood>, air], [<item:botania:livingwood>, air, <item:botania:livingwood>], [<item:botania:livingwood>, <item:botania:livingwood>, <item:botania:livingwood>]]);
shaped("bifrost_pane", <item:botania:bifrost_pane> * 8, [[<item:botania:bifrost_perm>, <item:botania:bifrost_perm>], [<item:botania:bifrost_perm>, <item:botania:bifrost_perm>]]);
shaped("black_hole_talisman", <item:botania:black_hole_talisman>, [[air, <item:botania:life_essence>, air], [<item:botania:elementium_ingot>, <item:botania:ender_air_bottle>, <item:botania:elementium_ingot>], [air, <item:botania:elementium_ingot>, air]]);
shaped("cacophonium", <item:botania:cacophonium>, [[air, <item:minecraft:gold_ingot>, air], [<item:minecraft:gold_ingot>, <item:minecraft:note_block>, <item:minecraft:gold_ingot>], [<item:minecraft:gold_ingot>, <item:minecraft:gold_ingot>, air]]);
shaped("clip", <item:botania:clip>, [[air, <item:botania:dreamwood>, air], [<item:botania:dreamwood>, air, <item:botania:dreamwood>], [<item:botania:dreamwood>, <item:botania:dreamwood>, air]]);
shaped("corporea_index", <item:botania:forest_eye>, [[<item:botania:ender_air_bottle>, <item:minecraft:obsidian>, <item:botania:ender_air_bottle>], [<item:minecraft:obsidian>, <item:botania:corporea_spark>, <item:minecraft:obsidian>], [<item:botania:ender_air_bottle>, <item:minecraft:obsidian>, <item:botania:ender_air_bottle>]]);
shaped("diluted_pool", <item:botania:diluted_pool>, [[<item:botania:livingrock_slab>, air, <item:botania:livingrock_slab>], [<item:botania:livingrock_slab>, <item:botania:livingrock_slab>, <item:botania:livingrock_slab>]]);
shaped("drum_canopy", <item:botania:drum_canopy>, [[<item:botania:livingwood>, <item:minecraft:leather>, <item:botania:livingwood>], [<item:botania:livingwood>, <item:botania:horn_leaves>, <item:botania:livingwood>], [<item:botania:livingwood>, <item:minecraft:leather>, <item:botania:livingwood>]]);
shaped("drum_gathering", <item:botania:drum_gathering>, [[<item:botania:dreamwood>, <item:minecraft:leather>, <item:botania:dreamwood>], [<item:botania:dreamwood>, <item:botania:elementium_ingot>, <item:botania:dreamwood>], [<item:botania:dreamwood>, <item:minecraft:leather>, <item:botania:dreamwood>]]);
shaped("drum_wild", <item:botania:drum_wild>, [[<item:botania:livingwood>, <item:minecraft:leather>, <item:botania:livingwood>], [<item:botania:livingwood>, <item:botania:horn_grass>, <item:botania:livingwood>], [<item:botania:livingwood>, <item:minecraft:leather>, <item:botania:livingwood>]]);
shaped("elementium_shears", <item:botania:elementium_shears>, [[air, <item:botania:elementium_ingot>], [<item:botania:elementium_ingot>, air]]);
shaped("elf_glass_pane", <item:botania:elf_glass_pane> * 8, [[<item:botania:elf_glass>, <item:botania:elf_glass>], [<item:botania:elf_glass>, <item:botania:elf_glass>]]);
shaped("elven_spreader", <item:botania:elven_spreader>, [[<item:botania:dreamwood>, <item:botania:dreamwood>, <item:botania:dreamwood>], [<item:botania:elementium_ingot>, <tag:items:botania:petals>, air], [<item:botania:dreamwood>, <item:botania:dreamwood>, <item:botania:dreamwood>]]);
shaped("fabulous_pool", <item:botania:fabulous_pool>, [[<item:botania:shimmerrock>, air, <item:botania:shimmerrock>], [<item:botania:shimmerrock>, <item:botania:shimmerrock>, <item:botania:shimmerrock>]]);
shaped("flower_bag", <item:botania:flower_bag>, [[air, <item:minecraft:string>, air], [<item:minecraft:rabbit_hide>, <tag:items:botania:petals>, <item:minecraft:rabbit_hide>], [air, <item:minecraft:rabbit_hide>, air]]);
shaped("forest_eye", <item:botania:forest_eye>, [[<item:botania:manasteel_ingot>, <item:botania:livingrock>, <item:botania:manasteel_ingot>], [<item:botania:livingrock>, <item:minecraft:ender_eye>, <item:botania:livingrock>], [<item:botania:manasteel_ingot>, <item:botania:livingrock>, <item:botania:manasteel_ingot>]]);
shaped("gaia_pylon", <item:botania:gaia_pylon>, [[air, <item:botania:pixie_dust>, air], [<item:botania:elementium_ingot>, <item:botania:natura_pylon>, <item:botania:elementium_ingot>], [air, <item:botania:pixie_dust>, air]]);
shaped("horn_grass", <item:botania:horn_grass>, [[air, <item:botania:livingwood>, air], [<item:botania:livingwood>, air, <item:botania:livingwood>], [<item:botania:livingwood>, <item:botania:livingwood>, air]]);
shaped("hourglass", <item:botania:hourglass>, [[<item:minecraft:gold_ingot>, <item:botania:mana_glass>, <item:minecraft:gold_ingot>], [<item:minecraft:redstone>, <item:botania:manasteel_ingot>, <item:minecraft:redstone>], [<item:minecraft:gold_ingot>, <item:botania:mana_glass>, <item:minecraft:gold_ingot>]]);
shaped("laputa_shard", <item:botania:laputa_shard>, [[<item:botania:life_essence>, <item:minecraft:prismarine_crystals>, <item:botania:life_essence>], [<item:minecraft:prismarine_crystals>, <item:botania:dragonstone>, <item:minecraft:prismarine_crystals>], [<item:botania:life_essence>, <item:minecraft:prismarine_crystals>, <item:botania:life_essence>]]);
shaped("lens_normal", <item:botania:lens_normal>, [[air, <item:botania:manasteel_ingot>, air], [<item:botania:manasteel_ingot>, <tag:items:forge:glass>, <item:botania:manasteel_ingot>], [air, <item:botania:manasteel_ingot>, air]]);
shaped("light_launcher", <item:botania:light_launcher>, [[<item:botania:dreamwood>, <item:botania:dreamwood>, <item:botania:dreamwood>], [<item:botania:dreamwood>, <item:botania:light_relay>, <item:botania:dreamwood>]]);
shaped("mana_bomb", <item:botania:mana_bomb>, [[<item:botania:livingwood>, <item:minecraft:tnt>, <item:botania:livingwood>], [<item:minecraft:tnt>, <item:botania:life_essence>, <item:minecraft:tnt>], [<item:botania:livingwood>, <item:minecraft:tnt>, <item:botania:livingwood>]]);
shaped("mana_detector", <item:botania:mana_detector>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:minecraft:comparator>, air, <item:minecraft:comparator>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("mana_distributor", <item:botania:mana_distributor>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:manasteel_ingot>, air, <item:botania:manasteel_ingot>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("mana_fluxfield", <item:botania:mana_fluxfield>, [[<item:botania:livingrock>, <item:minecraft:redstone_block>, <item:botania:livingrock>], [<item:minecraft:redstone_block>, <item:botania:manasteel_ingot>, <item:minecraft:redstone_block>], [<item:botania:livingrock>, <item:minecraft:redstone_block>, <item:botania:livingrock>]]);
shaped("mana_glass_pane", <item:botania:mana_glass_pane> * 8, [[<item:botania:mana_glass>, <item:botania:mana_glass>], [<item:botania:mana_glass>, <item:botania:mana_glass>]]);
shaped("mana_gun", <item:botania:mana_gun>, [[<item:botania:redstone_spreader>, <item:botania:rune_mana>, <item:botania:mana_diamond>], [air, <item:botania:livingwood>, <item:minecraft:tnt>], [air, air, <item:botania:livingwood>]]);
shaped("mana_pool", <item:botania:mana_pool>, [[<item:botania:livingrock>, air, <item:botania:livingrock>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("mana_pylon", <item:botania:mana_pylon>, [[air, <item:minecraft:gold_ingot>, air], [<item:botania:manasteel_ingot>, <item:botania:mana_diamond>, <item:botania:manasteel_ingot>], [air, <item:minecraft:gold_ingot>, air]]);
shaped("mana_spreader", <item:botania:mana_spreader>, [[<item:botania:livingwood>, <item:botania:livingwood>, <item:botania:livingwood>], [<item:minecraft:gold_ingot>, <tag:items:botania:petals>, air], [<item:botania:livingwood>, <item:botania:livingwood>, <item:botania:livingwood>]]);
shaped("mana_void", <item:botania:mana_void>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:minecraft:obsidian>, air, <item:minecraft:obsidian>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("manasteel_shears", <item:botania:manasteel_shears>, [[air, <item:botania:manasteel_ingot>], [<item:botania:manasteel_ingot>, air]]);
shaped("natura_pylon", <item:botania:natura_pylon>, [[air, <item:minecraft:ender_eye>, air], [<item:botania:terrasteel_ingot>, <item:botania:mana_pylon>, <item:botania:terrasteel_ingot>], [air, <item:minecraft:ender_eye>, air]]);
shaped("obedience_stick", <item:botania:obedience_stick>, [[air, air, <item:botania:manasteel_ingot>], [air, <item:botania:livingwood_twig>, air], [<item:botania:livingwood_twig>, air, air]]);
shaped("open_bucket", <item:botania:open_bucket>, [[<item:botania:elementium_ingot>, air, <item:botania:elementium_ingot>], [air, <item:botania:elementium_ingot>, air]]);
shaped("pattern_1_1", <item:botania:pattern_1_1>, [[<item:botania:placeholder>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>]]);
shaped("pattern_1_2", <item:botania:pattern_1_2>, [[<item:botania:placeholder>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:botania:placeholder>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>]]);
shaped("pattern_1_3", <item:botania:pattern_1_3>, [[<item:botania:placeholder>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:botania:placeholder>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:botania:placeholder>, <item:minecraft:redstone>, <item:minecraft:redstone>]]);
shaped("pattern_2_1", <item:botania:pattern_2_1>, [[<item:botania:placeholder>, <item:botania:placeholder>, <item:minecraft:redstone>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>]]);
shaped("pattern_2_2", <item:botania:pattern_2_2>, [[<item:botania:placeholder>, <item:botania:placeholder>, <item:minecraft:redstone>], [<item:botania:placeholder>, <item:botania:placeholder>, <item:minecraft:redstone>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>]]);
shaped("pattern_2_3", <item:botania:pattern_2_3>, [[<item:botania:placeholder>, <item:botania:placeholder>, <item:minecraft:redstone>], [<item:botania:placeholder>, <item:botania:placeholder>, <item:minecraft:redstone>], [<item:botania:placeholder>, <item:botania:placeholder>, <item:minecraft:redstone>]]);
shaped("pattern_3_1", <item:botania:pattern_3_1>, [[<item:botania:placeholder>, <item:botania:placeholder>, <item:botania:placeholder>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>]]);
shaped("pattern_3_2", <item:botania:pattern_3_2>, [[<item:botania:placeholder>, <item:botania:placeholder>, <item:botania:placeholder>], [<item:botania:placeholder>, <item:botania:placeholder>, <item:botania:placeholder>], [<item:minecraft:redstone>, <item:minecraft:redstone>, <item:minecraft:redstone>]]);
shaped("prism", <item:botania:prism>, [[<tag:items:forge:glass>, <item:minecraft:prismarine_crystals>, <tag:items:forge:glass>], [<tag:items:forge:glass>, <item:botania:spectral_platform>, <tag:items:forge:glass>], [<tag:items:forge:glass>, <item:minecraft:prismarine_crystals>, <tag:items:forge:glass>]]);
shaped("pump", <item:botania:pump>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:manasteel_ingot>, <item:minecraft:bucket>, <item:botania:manasteel_ingot>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("red_string_comparator", <item:botania:red_string_comparator>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:livingrock>, <item:minecraft:comparator>, <item:botania:red_string>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("red_string_container", <item:botania:red_string_container>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:livingrock>, <tag:items:forge:chests>, <item:botania:red_string>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("red_string_dispenser", <item:botania:red_string_dispenser>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:livingrock>, <item:minecraft:dispenser>, <item:botania:red_string>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("red_string_fertilizer", <item:botania:red_string_fertilizer>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:livingrock>, <item:botania:fertilizer>, <item:botania:red_string>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("red_string_interceptor", <item:botania:red_string_interceptor>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:livingrock>, <item:minecraft:stone_button>, <item:botania:red_string>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("red_string_relay", <item:botania:red_string_relay>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:livingrock>, <item:botania:mana_spreader>, <item:botania:red_string>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("runic_altar", <item:botania:runic_altar>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:livingrock>, <item:botania:mana_diamond>, <item:botania:livingrock>]]);
shaped("sextant", <item:botania:sextant>, [[<item:botania:manasteel_ingot>, <item:botania:livingwood_twig>, <item:botania:manasteel_ingot>], [<item:botania:manasteel_ingot>, <item:botania:livingwood_twig>, <item:botania:livingwood_twig>], [<item:botania:manasteel_ingot>, <item:botania:manasteel_ingot>, <item:botania:manasteel_ingot>]]);
shaped("slime_bottle", <item:botania:slime_bottle>, [[air, <item:botania:elf_glass>, air], [<item:botania:elementium_ingot>, <tag:items:forge:slimeballs>, <item:botania:elementium_ingot>], [air, <item:botania:elementium_ingot>, air]]);
shaped("spark_changer", <item:botania:spark_changer>, [[<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>], [<item:botania:elementium_ingot>, air, <item:botania:elementium_ingot>], [<item:botania:livingrock>, <item:botania:livingrock>, <item:botania:livingrock>]]);
shaped("spawner_claw", <item:botania:spawner_claw>, [[<item:minecraft:prismarine_crystals>, <item:botania:elementium_ingot>, <item:minecraft:prismarine_crystals>], [<item:minecraft:prismarine_crystals>, <item:botania:manasteel_block>, <item:minecraft:prismarine_crystals>], [<item:minecraft:prismarine_crystals>, <item:botania:ender_air_bottle>, <item:minecraft:prismarine_crystals>]]);
shaped("spectral_platform", <item:botania:spectral_platform>, [[<item:botania:dreamwood>, <item:botania:dreamwood>, <item:botania:dreamwood>], [<item:botania:dreamwood>, <item:botania:mana_pearl>, <item:botania:dreamwood>]]);
shaped("starfield", <item:botania:starfield>, [[<item:botania:elementium_ingot>, <item:botania:elementium_ingot>, <item:botania:elementium_ingot>], [<item:botania:elementium_ingot>, <item:minecraft:obsidian>, <item:botania:elementium_ingot>]]);
shaped("terra_plate", <item:botania:terra_plate>, [[<item:minecraft:lapis_block>, <item:minecraft:lapis_block>, <item:minecraft:lapis_block>], [<item:botania:rune_water>, <item:botania:manasteel_block>, <item:botania:rune_fire>], [<item:botania:rune_air>, <item:botania:rune_mana>, <item:botania:rune_earth>]]);
shaped("teru_teru_bozu", <item:botania:teru_teru_bozu>, [[air, <item:botania:manaweave_cloth>, air], [<item:botania:manaweave_cloth>, air, <item:botania:manaweave_cloth>], [<item:botania:manaweave_cloth>, <item:botania:manaweave_cloth>, <item:botania:manaweave_cloth>]]);
shapeless("agricarnation", <item:botania:floating_agricarnation>, [<item:botania:agricarnation>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("agricarnation_chibi", <item:botania:floating_agricarnation_chibi>, [<item:botania:agricarnation_chibi>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("animated_torch", <item:botania:animated_torch>, [<item:minecraft:redstone_torch>, <item:botania:mana_powder>]);
shapeless("auto_crafting_halo", <item:botania:auto_crafting_halo>, [<item:botania:crafting_halo>, <item:botania:mana_diamond>]);
shapeless("azulejo", <item:botania:azulejo_0>, [<tag:items:forge:storage_blocks/quartz>, <item:minecraft:lapis_lazuli>]);
shapeless("bauble_box", <item:botania:bauble_box>, [<tag:items:forge:chests>, <item:botania:manasteel_ingot>, <item:minecraft:gold_ingot>]);
shapeless("bellethorn", <item:botania:floating_bellethorn>, [<item:botania:bellethorn>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("bellethorn_chibi", <item:botania:floating_bellethorn_chibi>, [<item:botania:bellethorn_chibi>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("bergamute", <item:botania:floating_bergamute>, [<item:botania:bergamute>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("bifrost_perm", <item:botania:bifrost_perm>, [<item:botania:rainbow_rod>, <item:botania:elf_glass>]);
shapeless("black_pavement", <item:botania:black_pavement> * 3, [<item:botania:livingrock>, <item:minecraft:cobblestone>, <item:minecraft:gravel>, <item:minecraft:ink_sac>]);
shapeless("blue_pavement", <item:botania:blue_pavement> * 3, [<item:botania:livingrock>, <item:minecraft:cobblestone>, <item:minecraft:gravel>, <item:minecraft:lapis_lazuli>]);
shapeless("bubbell", <item:botania:floating_bubbell>, [<item:botania:bubbell>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("bubbell_chibi", <item:botania:floating_bubbell_chibi>, [<item:botania:bubbell_chibi>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("cell_block", <item:botania:cell_block>, [<item:minecraft:cactus>, <item:minecraft:carrot>, <item:minecraft:potato>, <item:minecraft:beetroot>]);
shapeless("corporea_block", <item:botania:corporea_block>, [<item:botania:livingrock>, <item:botania:corporea_spark>]);
shapeless("corporea_brick", <item:botania:corporea_brick>, [<item:botania:livingrock_bricks>, <item:botania:corporea_spark>]);
shapeless("corporea_crystal_cube", <item:botania:corporea_crystal_cube>, [<item:botania:elf_glass>, <item:botania:corporea_spark>]);
shapeless("corporea_funnel", <item:botania:corporea_funnel>, [<item:minecraft:dropper>, <item:botania:corporea_spark>]);
shapeless("corporea_interceptor", <item:botania:corporea_interceptor>, [<item:minecraft:redstone_block>, <item:botania:corporea_spark>]);
shapeless("corporea_retainer", <item:botania:corporea_retainer>, [<tag:items:forge:chests>, <item:botania:corporea_spark>]);
shapeless("corporea_spark", <item:botania:corporea_spark>, [<item:botania:spark>, <item:botania:pixie_dust>]);
shapeless("corporea_spark_master", <item:botania:corporea_spark_master>, [<item:botania:corporea_spark>, <item:botania:dragonstone>]);
shapeless("crafting_halo", <item:botania:crafting_halo>, [<item:minecraft:crafting_table>, <item:botania:manasteel_ingot>, <item:botania:mana_pearl>]);
shapeless("daffomill", <item:botania:floating_daffomill>, [<item:botania:daffomill>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("dandelifeon", <item:botania:floating_dandelifeon>, [<item:botania:dandelifeon>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("detector_light_relay", <item:botania:detector_light_relay>, [<item:botania:light_relay>, <item:minecraft:redstone>]);
shapeless("divining_rod", <item:botania:divining_rod>, [<item:botania:livingwood_twig>, <item:botania:rune_earth>, <item:botania:mana_diamond>]);
shapeless("dreadthorn", <item:botania:floating_dreadthorn>, [<item:botania:dreadthorn>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("dry_seeds", <item:botania:dry_seeds>, [<item:botania:grass_seeds>, <item:minecraft:dead_bush>]);
shapeless("ender_hand", <item:botania:ender_hand>, [<item:minecraft:ender_chest>, <item:minecraft:leather>, <item:botania:mana_pearl>]);
shapeless("endoflame", <item:botania:floating_endoflame>, [<item:botania:endoflame>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("entropinnyum", <item:botania:floating_entropinnyum>, [<item:botania:entropinnyum>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("exchange_rod", <item:botania:exchange_rod>, [<item:botania:fire_rod>, <item:botania:rune_earth>]);
shapeless("exoflame", <item:botania:floating_exoflame>, [<item:botania:exoflame>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("fallen_kanade", <item:botania:floating_fallen_kanade>, [<item:botania:fallen_kanade>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("fel_pumpkin", <item:botania:fel_pumpkin>, [<item:minecraft:carved_pumpkin>, <item:minecraft:rotten_flesh>, <item:minecraft:bone>, <item:minecraft:gunpowder>]);
shapeless("fertilizer", <item:botania:fertilizer>, [<item:minecraft:bone_meal>, <tag:items:forge:dyes>]);
shapeless("fire_rod", <item:botania:fire_rod>, [<item:botania:livingwood_twig>, <item:botania:rune_fire>, <item:minecraft:blaze_powder>]);
shapeless("flare_chakram", <item:botania:flare_chakram>, [<item:botania:thorn_chakram>, <item:minecraft:blaze_powder>]);
shapeless("fork_light_relay", <item:botania:fork_light_relay>, [<item:botania:light_relay>, <item:minecraft:redstone_torch>]);
shapeless("gaia_ingot", <item:botania:gaia_ingot>, [<item:botania:terrasteel_ingot>, <item:botania:life_essence>]);
shapeless("gaia_spreader", <item:botania:gaia_spreader>, [<item:botania:elven_spreader>, <item:botania:life_essence>]);
shapeless("golden_seeds", <item:botania:golden_seeds>, [<item:botania:grass_seeds>, <item:minecraft:wheat>]);
shapeless("gourmaryllis", <item:botania:floating_gourmaryllis>, [<item:botania:gourmaryllis>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("green_pavement", <item:botania:green_pavement> * 3, [<item:botania:livingrock>, <item:minecraft:cobblestone>, <item:minecraft:gravel>, <item:quark:cactus_paste>]);
shapeless("heisei_dream", <item:botania:floating_heisei_dream>, [<item:botania:heisei_dream>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("hopperhock", <item:botania:floating_hopperhock>, [<item:botania:hopperhock>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("hopperhock_chibi", <item:botania:floating_hopperhock_chibi>, [<item:botania:hopperhock_chibi>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("horn_leaves", <item:botania:horn_leaves>, [<item:botania:horn_grass>, <tag:items:minecraft:leaves>]);
shapeless("horn_snow", <item:botania:horn_snow>, [<item:botania:horn_grass>, <item:minecraft:snowball>]);
shapeless("hyacidus", <item:botania:floating_hyacidus>, [<item:botania:hyacidus>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("hydroangeas", <item:botania:floating_hydroangeas>, [<item:botania:hydroangeas>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("incense_plate", <item:botania:incense_plate>, [<item:botania:livingwood>, <item:botania:livingwood_slab>]);
shapeless("infused_seeds", <item:botania:infused_seeds>, [<item:botania:grass_seeds>, <item:minecraft:prismarine_shard>]);
shapeless("jaded_amaranthus", <item:botania:floating_jaded_amaranthus>, [<item:botania:jaded_amaranthus>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("jiyuulia", <item:botania:floating_jiyuulia>, [<item:botania:jiyuulia>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("keep_ivy", <item:botania:keep_ivy>, [<item:botania:pixie_dust>, <item:minecraft:vine>, <item:botania:ender_air_bottle>]);
shapeless("kekimurus", <item:botania:floating_kekimurus>, [<item:botania:kekimurus>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("lens_bounce", <item:botania:lens_bounce>, [<item:botania:lens_normal>, <item:botania:rune_summer>]);
shapeless("lens_damage", <item:botania:lens_damage>, [<item:botania:lens_normal>, <item:botania:rune_wrath>]);
shapeless("lens_efficiency", <item:botania:lens_efficiency>, [<item:botania:lens_normal>, <item:botania:rune_water>]);
shapeless("lens_explosive", <item:botania:lens_explosive>, [<item:botania:lens_normal>, <item:botania:rune_envy>]);
shapeless("lens_fire", <item:botania:lens_fire>, [<item:botania:lens_normal>, <item:minecraft:fire_charge>]);
shapeless("lens_firework", <item:botania:lens_firework>, [<item:botania:lens_normal>, <item:minecraft:firework_rocket>]);
shapeless("lens_flare", <item:botania:lens_flare>, [<item:botania:lens_normal>, <item:botania:elf_glass>]);
shapeless("lens_gravity", <item:botania:lens_gravity>, [<item:botania:lens_normal>, <item:botania:rune_winter>]);
shapeless("lens_influence", <item:botania:lens_influence>, [<item:botania:lens_normal>, <item:minecraft:gold_ingot>]);
shapeless("lens_light", <item:botania:lens_light>, [<item:botania:lens_normal>, <item:minecraft:glowstone_dust>]);
shapeless("lens_magnet", <item:botania:lens_magnet>, [<item:botania:lens_normal>, <item:minecraft:iron_ingot>]);
shapeless("lens_messenger", <item:botania:lens_messenger>, [<item:botania:lens_normal>, <item:minecraft:paper>]);
shapeless("lens_mine", <item:botania:lens_mine>, [<item:botania:lens_normal>, <item:minecraft:piston>]);
shapeless("lens_paint", <item:botania:lens_paint>, [<item:botania:lens_normal>, <tag:items:minecraft:wool>]);
shapeless("lens_phantom", <item:botania:lens_phantom>, [<item:botania:lens_normal>, <item:botania:abstruse_platform>]);
shapeless("lens_piston", <item:botania:lens_piston>, [<item:botania:lens_normal>, <item:botania:piston_relay>]);
shapeless("lens_power", <item:botania:lens_power>, [<item:botania:lens_normal>, <item:botania:rune_fire>]);
shapeless("lens_redirect", <item:botania:lens_redirect>, [<item:botania:lens_normal>, <item:botania:livingwood>]);
shapeless("lens_speed", <item:botania:lens_speed>, [<item:botania:lens_normal>, <item:botania:rune_air>]);
shapeless("lens_time", <item:botania:lens_time>, [<item:botania:lens_normal>, <item:botania:rune_earth>]);
shapeless("lens_tripwire", <item:botania:lens_tripwire>, [<item:botania:lens_normal>, <item:minecraft:tripwire_hook>]);
shapeless("lens_warp", <item:botania:lens_warp>, [<item:botania:lens_normal>, <item:botania:pixie_dust>]);
shapeless("lens_weight", <item:botania:lens_weight>, [<item:botania:lens_normal>, <item:minecraft:prismarine_crystals>]);
shapeless("light_relay", <item:botania:light_relay>, [<item:botania:red_string>, <item:botania:dragonstone>, <item:minecraft:glowstone_dust>]);
shapeless("loonium", <item:botania:floating_loonium>, [<item:botania:loonium>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("mana_mirror", <item:botania:mana_mirror>, [<item:botania:livingwood_twig>, <item:botania:mana_pearl>, <item:botania:mana_tablet>]);
shapeless("marimorphosis", <item:botania:floating_marimorphosis>, [<item:botania:marimorphosis>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("marimorphosis_chibi", <item:botania:floating_marimorphosis_chibi>, [<item:botania:marimorphosis_chibi>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("medumone", <item:botania:floating_medumone>, [<item:botania:medumone>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("munchdew", <item:botania:floating_munchdew>, [<item:botania:munchdew>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("mutated_seeds", <item:botania:mutated_seeds>, [<item:botania:grass_seeds>, <item:minecraft:spider_eye>]);
shapeless("mycelium_seeds", <item:botania:mycelium_seeds>, [<item:botania:grass_seeds>, <item:minecraft:mycelium>]);
shapeless("narslimmus", <item:botania:floating_narslimmus>, [<item:botania:narslimmus>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("phantom_ink", <item:botania:phantom_ink> * 4, [<item:botania:mana_pearl>, <tag:items:botania:petals>, <tag:items:forge:glass>, <item:minecraft:glass_bottle>, <item:minecraft:glass_bottle>, <item:minecraft:glass_bottle>, <item:minecraft:glass_bottle>]);
shapeless("placeholder", <item:botania:placeholder>, [<item:minecraft:crafting_table>, <item:botania:livingrock>]);
shapeless("podzol_seeds", <item:botania:podzol_seeds>, [<item:botania:grass_seeds>, <item:minecraft:podzol>]);
shapeless("pool_minecart", <item:botania:pool_minecart>, [<item:minecraft:minecart>, <item:botania:mana_pool>]);
shapeless("pure_daisy", <item:botania:floating_pure_daisy>, [<item:botania:pure_daisy>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("rafflowsia", <item:botania:floating_rafflowsia>, [<item:botania:rafflowsia>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("rainbow_rod", <item:botania:rainbow_rod>, [<item:botania:elementium_ingot>, <item:botania:dragonstone>, <item:botania:terrasteel_ingot>, <item:botania:pixie_dust>]);
shapeless("rannuncarpus", <item:botania:floating_rannuncarpus>, [<item:botania:rannuncarpus>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("rannuncarpus_chibi", <item:botania:floating_rannuncarpus_chibi>, [<item:botania:rannuncarpus_chibi>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("red_pavement", <item:botania:red_pavement> * 3, [<item:botania:livingrock>, <item:minecraft:cobblestone>, <item:minecraft:gravel>, <item:minecraft:redstone>]);
shapeless("red_string", <item:botania:red_string>, [<item:minecraft:string>, <item:minecraft:redstone_block>, <item:botania:pixie_dust>, <item:botania:ender_air_bottle>]);
shapeless("redstone_root", <item:botania:redstone_root>, [<item:minecraft:redstone>, <item:minecraft:grass>]);
shapeless("redstone_spreader", <item:botania:redstone_spreader>, [<item:botania:mana_spreader>, <item:minecraft:redstone>]);
shapeless("rosa_arcana", <item:botania:floating_rosa_arcana>, [<item:botania:rosa_arcana>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("scorched_seeds", <item:botania:scorched_seeds>, [<item:botania:grass_seeds>, <item:minecraft:blaze_powder>]);
shapeless("shimmerrock", <item:botania:shimmerrock>, [<item:botania:livingrock>, <item:botania:bifrost_perm>]);
shapeless("shulk_me_not", <item:botania:floating_shulk_me_not>, [<item:botania:shulk_me_not>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("skydirt_rod", <item:botania:skydirt_rod>, [<item:botania:dirt_rod>, <item:botania:pixie_dust>]);
shapeless("smelt_rod", <item:botania:smelt_rod>, [<item:botania:divining_rod>, <item:botania:rune_fire>]);
shapeless("solegnolia", <item:botania:floating_solegnolia>, [<item:botania:solegnolia>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("solegnolia_chibi", <item:botania:floating_solegnolia_chibi>, [<item:botania:solegnolia_chibi>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("spark", <item:botania:spark>, [<tag:items:botania:petals>, <item:minecraft:blaze_powder>, <item:minecraft:gold_ingot>]);
shapeless("spark_upgrade_dispersive", <item:botania:spark_upgrade_dispersive>, [<item:botania:pixie_dust>, <item:botania:manasteel_ingot>, <item:botania:rune_water>]);
shapeless("spark_upgrade_dominant", <item:botania:spark_upgrade_dominant>, [<item:botania:pixie_dust>, <item:botania:manasteel_ingot>, <item:botania:rune_fire>]);
shapeless("spark_upgrade_isolated", <item:botania:spark_upgrade_isolated>, [<item:botania:pixie_dust>, <item:botania:manasteel_ingot>, <item:botania:rune_air>]);
shapeless("spark_upgrade_recessive", <item:botania:spark_upgrade_recessive>, [<item:botania:pixie_dust>, <item:botania:manasteel_ingot>, <item:botania:rune_earth>]);
shapeless("spectranthemum", <item:botania:floating_spectranthemum>, [<item:botania:spectranthemum>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("spectrolus", <item:botania:floating_spectrolus>, [<item:botania:spectrolus>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("tangleberrie", <item:botania:floating_tangleberrie>, [<item:botania:tangleberrie>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("terraform_rod", <item:botania:terraform_rod>, [<item:botania:dirt_rod>, <item:botania:terrasteel_ingot>]);
shapeless("thermalily", <item:botania:floating_thermalily>, [<item:botania:thermalily>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("tigerseye", <item:botania:floating_tigerseye>, [<item:botania:tigerseye>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("toggle_light_relay", <item:botania:toggle_light_relay>, [<item:botania:light_relay>, <item:minecraft:lever>]);
shapeless("tornado_rod", <item:botania:tornado_rod>, [<item:botania:livingwood_twig>, <item:botania:rune_air>, <item:minecraft:feather>]);
shapeless("vinculotus", <item:botania:floating_vinculotus>, [<item:botania:vinculotus>, <item:minecraft:dirt>, <item:botania:grass_seeds>]);
shapeless("virus_necrodermal", <item:botania:virus_necrodermal>, [<item:botania:pixie_dust>, <item:minecraft:fermented_spider_eye>, <item:botania:vine_ball>, <item:minecraft:zombie_head>]);
shapeless("virus_nullodermal", <item:botania:virus_nullodermal>, [<item:botania:pixie_dust>, <item:minecraft:fermented_spider_eye>, <item:botania:vine_ball>, <item:minecraft:skeleton_skull>]);
shapeless("vivid_seeds", <item:botania:vivid_seeds>, [<item:botania:grass_seeds>, <item:quark:cactus_paste>]);
shapeless("water_rod", <item:botania:water_rod>, [<item:botania:livingwood_twig>, <item:botania:rune_water>, <item:minecraft:water_bucket>]);
shapeless("white_pavement", <item:botania:white_pavement> * 3, [<item:botania:livingrock>, <item:minecraft:cobblestone>, <item:minecraft:gravel>, <item:minecraft:bone_meal>]);
shapeless("world_seed", <item:botania:world_seed> * 4, [<item:minecraft:grass_block>, <item:minecraft:wheat_seeds>, <item:botania:dragonstone>]);
shapeless("yellow_pavement", <item:botania:yellow_pavement> * 3, [<item:botania:livingrock>, <item:minecraft:cobblestone>, <item:minecraft:gravel>, <item:minecraft:glowstone_dust>]);
shovel("cobble_rod", <item:minecraft:cobblestone>, <item:botania:cobble_rod>, <item:botania:livingwood_twig>);
shovel("dirt_rod", <item:minecraft:dirt>, <item:botania:dirt_rod>, <item:botania:livingwood_twig>);
shovel("dragonstone", <item:botania:dragonstone>, <item:botania:gravity_rod>, <item:botania:dreamwood_twig>);
shovel("slingshot", <item:botania:rune_air>, <item:botania:slingshot>, <item:botania:livingwood_twig>);
smallCompressWithUndo("blaze_quartz", <item:botania:quartz_blaze>, <item:botania:blaze_quartz>);
smallCompressWithUndo("dark_quartz", <item:botania:quartz_dark>, <item:botania:dark_quartz>);
smallCompressWithUndo("elf_quartz", <item:botania:quartz_elven>, <item:botania:elf_quartz>);
smallCompressWithUndo("lavender_quartz", <item:botania:quartz_lavender>, <item:botania:lavender_quartz>);
smallCompressWithUndo("mana_quartz", <item:botania:quartz_mana>, <item:botania:mana_quartz>);
smallCompressWithUndo("manaweave_cloth", <item:botania:mana_string>, <item:botania:manaweave_cloth>);
smallCompressWithUndo("red_quartz", <item:botania:quartz_red>, <item:botania:red_quartz>);
smallCompressWithUndo("sunny_quartz", <item:botania:quartz_sunny>, <item:botania:sunny_quartz>);
