#priority 2
import mods.jei.JEI;
JEI.hideCategory("appliedenergistics2:grinder");
JEI.hideCategory("botania:brewery");
JEI.hideCategory("botania:orechid");
JEI.hideCategory("botania:orechid_ignem");
JEI.hideCategory("botania:terra_plate");
JEI.hideCategory("cookingforblockheads:cow_jar");
JEI.hideCategory("cyclic:melter");
JEI.hideCategory("cyclic:solidifier");
JEI.hideCategory("industrialforegoing:bioreactor");
JEI.hideCategory("industrialforegoing:dissolution_chamber");
JEI.hideCategory("industrialforegoing:fluid_extractor");
JEI.hideCategory("industrialforegoing:laser_drill_fluid");
JEI.hideCategory("industrialforegoing:laser_drill_ore");
JEI.hideCategory("industrialforegoing:machine_produce");
JEI.hideCategory("industrialforegoing:mycelial_crimed");
JEI.hideCategory("industrialforegoing:mycelial_culinary");
JEI.hideCategory("industrialforegoing:mycelial_death");
JEI.hideCategory("industrialforegoing:mycelial_disenchantment");
JEI.hideCategory("industrialforegoing:mycelial_ender");
JEI.hideCategory("industrialforegoing:mycelial_explosive");
JEI.hideCategory("industrialforegoing:mycelial_frosty");
JEI.hideCategory("industrialforegoing:mycelial_furnace");
JEI.hideCategory("industrialforegoing:mycelial_halitosis");
JEI.hideCategory("industrialforegoing:mycelial_magma");
JEI.hideCategory("industrialforegoing:mycelial_meatallurgic");
JEI.hideCategory("industrialforegoing:mycelial_netherstar");
JEI.hideCategory("industrialforegoing:mycelial_pink");
JEI.hideCategory("industrialforegoing:mycelial_potion");
JEI.hideCategory("industrialforegoing:mycelial_rocket");
JEI.hideCategory("industrialforegoing:mycelial_slimey");
JEI.hideCategory("industrialforegoing:ore_fermenter");
JEI.hideCategory("industrialforegoing:ore_sieve");
JEI.hideCategory("industrialforegoing:ore_washer");
JEI.hideCategory("industrialforegoing:stonework");
JEI.hideCategory("industrialforegoing:stonework_generate");
JEI.hideCategory("jei:information");
JEI.hideCategory("mekanism:energized_smelter");
JEI.hideCategory("minecraft:anvil");
JEI.hideCategory("minecraft:brewing");
JEI.hideCategory("mysticalagriculture:reprocessor");
JEI.hideCategory("securitycraft:securitycraft_to_vanilla");
JEI.hideCategory("securitycraft:vanilla_to_securitycraft");
JEI.hideCategory("thermal:bottler");
JEI.hideCategory("thermal:brewer");
JEI.hideCategory("thermal:centrifuge");
JEI.hideCategory("thermal:chiller");
JEI.hideCategory("thermal:compression_fuel");
JEI.hideCategory("thermal:crucible");
JEI.hideCategory("thermal:furnace");
JEI.hideCategory("thermal:insolator");
JEI.hideCategory("thermal:insolator_catalyst");
JEI.hideCategory("thermal:lapidary_fuel");
JEI.hideCategory("thermal:magmatic_fuel");
JEI.hideCategory("thermal:numismatic_fuel");
JEI.hideCategory("thermal:press");
JEI.hideCategory("thermal:pulverizer");
JEI.hideCategory("thermal:pulverizer_catalyst");
JEI.hideCategory("thermal:pyrolyzer");
JEI.hideCategory("thermal:refinery");
JEI.hideCategory("thermal:rock_gen");
JEI.hideCategory("thermal:sawmill");
JEI.hideCategory("thermal:smelter");
JEI.hideCategory("thermal:smelter_catalyst");
JEI.hideCategory("thermal:stirling_fuel");
JEI.hideCategory("thermal:tree_extractor");
JEI.hideItem(<item:apotheosis:broadhead_arrow>);
JEI.hideItem(<item:apotheosis:explosive_arrow>);
JEI.hideItem(<item:appliedenergistics2:certus_crystal_seed>);
JEI.hideItem(<item:appliedenergistics2:crank>);
JEI.hideItem(<item:appliedenergistics2:creative_energy_cell>);
JEI.hideItem(<item:appliedenergistics2:creative_storage_cell>);
JEI.hideItem(<item:appliedenergistics2:debug_part_placer>);
JEI.hideItem(<item:appliedenergistics2:encoded_pattern>);
JEI.hideItem(<item:appliedenergistics2:flour>);
JEI.hideItem(<item:appliedenergistics2:fluix_crystal_seed>);
JEI.hideItem(<item:appliedenergistics2:grindstone>);
JEI.hideItem(<item:appliedenergistics2:nether_quartz_seed>);
JEI.hideItem(<item:appliedenergistics2:quartz_growth_accelerator>);
JEI.hideItem(<item:appliedenergistics2:sky_compass>);
JEI.hideItem(<item:appliedenergistics2:sky_dust>);
JEI.hideItem(<item:appliedenergistics2:vibration_chamber>);
JEI.hideItem(<item:appliedenergistics2:wooden_gear>);
JEI.hideItem(<item:botania:alchemy_catalyst>);
JEI.hideItem(<item:botania:brewery>);
JEI.hideItem(<item:botania:clayconia>);
JEI.hideItem(<item:botania:clayconia_chibi>);
JEI.hideItem(<item:botania:conjuration_catalyst>);
JEI.hideItem(<item:botania:creative_pool>);
JEI.hideItem(<item:botania:flask>);
JEI.hideItem(<item:botania:floating_clayconia>);
JEI.hideItem(<item:botania:floating_clayconia_chibi>);
JEI.hideItem(<item:botania:floating_orechid>);
JEI.hideItem(<item:botania:floating_orechid_ignem>);
JEI.hideItem(<item:botania:floating_pollidisiac>);
JEI.hideItem(<item:botania:ghost_rail>);
JEI.hideItem(<item:botania:infrangible_platform>);
JEI.hideItem(<item:botania:living_root>);
JEI.hideItem(<item:botania:orechid>);
JEI.hideItem(<item:botania:orechid_ignem>);
JEI.hideItem(<item:botania:pebble>);
JEI.hideItem(<item:botania:pestle_and_mortar>);
JEI.hideItem(<item:botania:pollidisiac>);
JEI.hideItem(<item:botania:root>);
JEI.hideItem(<item:botania:spawner_mover>);
JEI.hideItem(<item:botania:vial>);
JEI.hideItem(<item:botania:water_bowl>.withTag({Fluid: {FluidName: "minecraft:water" as string, Amount: 1000 as int}}));
JEI.hideItem(<item:charm:kiln>);
JEI.hideItem(<item:charm:netherite_nugget>);
JEI.hideItem(<item:chiselsandbits:bit_bag_dyed>);
JEI.hideItem(<item:chiselsandbits:mirrorprint_written>);
JEI.hideItem(<item:chiselsandbits:negativeprint_written>);
JEI.hideItem(<item:chiselsandbits:positiveprint_written>);
JEI.hideItem(<item:computercraft:computer_command>);
JEI.hideItem(<item:cyclic:anvil>);
JEI.hideItem(<item:cyclic:anvil_magma>);
JEI.hideItem(<item:cyclic:apple_bone>);
JEI.hideItem(<item:cyclic:apple_chocolate>);
JEI.hideItem(<item:cyclic:apple_chorus>);
JEI.hideItem(<item:cyclic:apple_diamond>);
JEI.hideItem(<item:cyclic:apple_emerald>);
JEI.hideItem(<item:cyclic:apple_ender>);
JEI.hideItem(<item:cyclic:apple_honey>);
JEI.hideItem(<item:cyclic:apple_iron>);
JEI.hideItem(<item:cyclic:apple_lapis>);
JEI.hideItem(<item:cyclic:apple_prismarine>);
JEI.hideItem(<item:cyclic:battery>);
JEI.hideItem(<item:cyclic:battery_infinite>);
JEI.hideItem(<item:cyclic:biomass>);
JEI.hideItem(<item:cyclic:biomass_bucket>);
JEI.hideItem(<item:cyclic:breaker>);
JEI.hideItem(<item:cyclic:cable_wrench>);
JEI.hideItem(<item:cyclic:cask>);
JEI.hideItem(<item:cyclic:carbon_paper>);
JEI.hideItem(<item:cyclic:charm_torch>);
JEI.hideItem(<item:cyclic:charm_torch_cave>);
JEI.hideItem(<item:cyclic:collector_fluid>);
JEI.hideItem(<item:cyclic:conveyor>);
JEI.hideItem(<item:cyclic:crafter>);
JEI.hideItem(<item:cyclic:crate>);
JEI.hideItem(<item:cyclic:crystal_axe>);
JEI.hideItem(<item:cyclic:crystal_boots>);
JEI.hideItem(<item:cyclic:crystal_chestplate>);
JEI.hideItem(<item:cyclic:crystal_helmet>);
JEI.hideItem(<item:cyclic:crystal_hoe>);
JEI.hideItem(<item:cyclic:crystal_leggings>);
JEI.hideItem(<item:cyclic:crystal_pickaxe>);
JEI.hideItem(<item:cyclic:crystal_shovel>);
JEI.hideItem(<item:cyclic:crystal_sword>);
JEI.hideItem(<item:cyclic:dropper>);
JEI.hideItem(<item:cyclic:emerald_axe>);
JEI.hideItem(<item:cyclic:emerald_boots>);
JEI.hideItem(<item:cyclic:emerald_chestplate>);
JEI.hideItem(<item:cyclic:emerald_helmet>);
JEI.hideItem(<item:cyclic:emerald_hoe>);
JEI.hideItem(<item:cyclic:emerald_leggings>);
JEI.hideItem(<item:cyclic:emerald_pickaxe>);
JEI.hideItem(<item:cyclic:emerald_shovel>);
JEI.hideItem(<item:cyclic:emerald_sword>);
JEI.hideItem(<item:cyclic:ender_bag>);
JEI.hideItem(<item:cyclic:ender_controller>);
JEI.hideItem(<item:cyclic:ender_shelf>);
JEI.hideItem(<item:cyclic:energy_pipe>);
JEI.hideItem(<item:cyclic:experience_food>);
JEI.hideItem(<item:cyclic:experience_pylon>);
JEI.hideItem(<item:cyclic:eye_redstone>);
JEI.hideItem(<item:cyclic:fisher>);
JEI.hideItem(<item:cyclic:flower_cyan>);
JEI.hideItem(<item:cyclic:fluid_pipe>);
JEI.hideItem(<item:cyclic:gem_amber>);
JEI.hideItem(<item:cyclic:gem_obsidian>);
JEI.hideItem(<item:cyclic:honey_bucket>);
JEI.hideItem(<item:cyclic:item_infinite>);
JEI.hideItem(<item:cyclic:item_pipe>);
JEI.hideItem(<item:cyclic:magic_net>);
JEI.hideItem(<item:cyclic:magma_bucket>);
JEI.hideItem(<item:cyclic:mason_cobble>);
JEI.hideItem(<item:cyclic:mason_iron>);
JEI.hideItem(<item:cyclic:mason_plate>);
JEI.hideItem(<item:cyclic:mason_steel>);
JEI.hideItem(<item:cyclic:mason_stone>);
JEI.hideItem(<item:cyclic:melter>);
JEI.hideItem(<item:cyclic:netherbrick_axe>);
JEI.hideItem(<item:cyclic:netherbrick_hoe>);
JEI.hideItem(<item:cyclic:netherbrick_pickaxe>);
JEI.hideItem(<item:cyclic:netherbrick_shovel>);
JEI.hideItem(<item:cyclic:netherbrick_sword>);
JEI.hideItem(<item:cyclic:peat_baked>);
JEI.hideItem(<item:cyclic:peat_farm>);
JEI.hideItem(<item:cyclic:peat_fuel>);
JEI.hideItem(<item:cyclic:peat_fuel_enriched>);
JEI.hideItem(<item:cyclic:peat_generator>);
JEI.hideItem(<item:cyclic:peat_unbaked>);
JEI.hideItem(<item:cyclic:placer>);
JEI.hideItem(<item:cyclic:placer_fluid>);
JEI.hideItem(<item:cyclic:sandstone_axe>);
JEI.hideItem(<item:cyclic:sandstone_hoe>);
JEI.hideItem(<item:cyclic:sandstone_pickaxe>);
JEI.hideItem(<item:cyclic:sandstone_shovel>);
JEI.hideItem(<item:cyclic:sandstone_sword>);
JEI.hideItem(<item:cyclic:shears_flint>);
JEI.hideItem(<item:cyclic:shears_obsidian>);
JEI.hideItem(<item:cyclic:slime_bucket>);
JEI.hideItem(<item:cyclic:solidifier>);
JEI.hideItem(<item:cyclic:storage_bag>);
JEI.hideItem(<item:cyclic:tank>);
JEI.hideItem(<item:cyclic:tile_transporter_empty>);
JEI.hideItem(<item:cyclic:toxic_carrot>);
JEI.hideItem(<item:cyclic:xpjuice_bucket>);
JEI.hideItem(<item:darkutils:item_grate>);
JEI.hideItem(<item:darkutils:redstone_randomizer>);
JEI.hideItem(<item:industrialforegoing:biofuel_bucket>);
JEI.hideItem(<item:industrialforegoing:biofuel_generator>);
JEI.hideItem(<item:industrialforegoing:bioreactor>);
JEI.hideItem(<item:industrialforegoing:conveyor>);
JEI.hideItem(<item:industrialforegoing:conveyor_blinking_upgrade>);
JEI.hideItem(<item:industrialforegoing:conveyor_bouncing_upgrade>);
JEI.hideItem(<item:industrialforegoing:conveyor_detection_upgrade>);
JEI.hideItem(<item:industrialforegoing:conveyor_dropping_upgrade>);
JEI.hideItem(<item:industrialforegoing:conveyor_extraction_upgrade>);
JEI.hideItem(<item:industrialforegoing:conveyor_insertion_upgrade>);
JEI.hideItem(<item:industrialforegoing:conveyor_splitting_upgrade>);
JEI.hideItem(<item:industrialforegoing:dark_glass>);
JEI.hideItem(<item:industrialforegoing:dissolution_chamber>);
JEI.hideItem(<item:industrialforegoing:dryrubber>);
JEI.hideItem(<item:industrialforegoing:ether_gas_bucket>);
JEI.hideItem(<item:industrialforegoing:fermentation_station>);
JEI.hideItem(<item:industrialforegoing:fermented_ore_meat_bucket>);
JEI.hideItem(<item:industrialforegoing:fluid_extractor>);
JEI.hideItem(<item:industrialforegoing:fluid_laser_base>);
JEI.hideItem(<item:industrialforegoing:fluid_sieving_machine>);
JEI.hideItem(<item:industrialforegoing:infinity_charger>);
JEI.hideItem(<item:industrialforegoing:laser_drill>);
JEI.hideItem(<item:industrialforegoing:laser_lens0>);
JEI.hideItem(<item:industrialforegoing:laser_lens10>);
JEI.hideItem(<item:industrialforegoing:laser_lens11>);
JEI.hideItem(<item:industrialforegoing:laser_lens12>);
JEI.hideItem(<item:industrialforegoing:laser_lens13>);
JEI.hideItem(<item:industrialforegoing:laser_lens14>);
JEI.hideItem(<item:industrialforegoing:laser_lens15>);
JEI.hideItem(<item:industrialforegoing:laser_lens1>);
JEI.hideItem(<item:industrialforegoing:laser_lens2>);
JEI.hideItem(<item:industrialforegoing:laser_lens3>);
JEI.hideItem(<item:industrialforegoing:laser_lens4>);
JEI.hideItem(<item:industrialforegoing:laser_lens5>);
JEI.hideItem(<item:industrialforegoing:laser_lens6>);
JEI.hideItem(<item:industrialforegoing:laser_lens7>);
JEI.hideItem(<item:industrialforegoing:laser_lens8>);
JEI.hideItem(<item:industrialforegoing:laser_lens9>);
JEI.hideItem(<item:industrialforegoing:latex_bucket>);
JEI.hideItem(<item:industrialforegoing:latex_processing_unit>);
JEI.hideItem(<item:industrialforegoing:machine_frame_advanced>);
JEI.hideItem(<item:industrialforegoing:machine_frame_pity>);
JEI.hideItem(<item:industrialforegoing:machine_frame_simple>);
JEI.hideItem(<item:industrialforegoing:machine_frame_supreme>);
JEI.hideItem(<item:industrialforegoing:material_stonework_factory>);
JEI.hideItem(<item:industrialforegoing:mycelial_crimed>);
JEI.hideItem(<item:industrialforegoing:mycelial_culinary>);
JEI.hideItem(<item:industrialforegoing:mycelial_death>);
JEI.hideItem(<item:industrialforegoing:mycelial_disenchantment>);
JEI.hideItem(<item:industrialforegoing:mycelial_ender>);
JEI.hideItem(<item:industrialforegoing:mycelial_explosive>);
JEI.hideItem(<item:industrialforegoing:mycelial_frosty>);
JEI.hideItem(<item:industrialforegoing:mycelial_furnace>);
JEI.hideItem(<item:industrialforegoing:mycelial_halitosis>);
JEI.hideItem(<item:industrialforegoing:mycelial_magma>);
JEI.hideItem(<item:industrialforegoing:mycelial_meatallurgic>);
JEI.hideItem(<item:industrialforegoing:mycelial_netherstar>);
JEI.hideItem(<item:industrialforegoing:mycelial_pink>);
JEI.hideItem(<item:industrialforegoing:mycelial_potion>);
JEI.hideItem(<item:industrialforegoing:mycelial_reactor>);
JEI.hideItem(<item:industrialforegoing:mycelial_rocket>);
JEI.hideItem(<item:industrialforegoing:mycelial_slimey>);
JEI.hideItem(<item:industrialforegoing:ore_laser_base>);
JEI.hideItem(<item:industrialforegoing:pink_slime_ingot>);
JEI.hideItem(<item:industrialforegoing:pitiful_generator>);
JEI.hideItem(<item:industrialforegoing:plastic>);
JEI.hideItem(<item:industrialforegoing:potion_brewer>);
JEI.hideItem(<item:industrialforegoing:raw_ore_meat_bucket>);
JEI.hideItem(<item:industrialforegoing:straw>);
JEI.hideItem(<item:industrialforegoing:tinydryrubber>);
JEI.hideItem(<item:industrialforegoing:washing_factory>);
JEI.hideItem(<item:inspirations:barometer>);
JEI.hideItem(<item:inspirations:cactus_seeds>);
JEI.hideItem(<item:inspirations:charged_arrow>);
JEI.hideItem(<item:inspirations:collector>);
JEI.hideItem(<item:inspirations:heartbeet>);
JEI.hideItem(<item:inspirations:north_compass>);
JEI.hideItem(<item:inspirations:photometer>);
JEI.hideItem(<item:inspirations:pipe>);
JEI.hideItem(<item:inspirations:redstone_book>);
JEI.hideItem(<item:inspirations:sugar_cane_seeds>);
JEI.hideItem(<item:ironchest:copper_to_iron_chest_upgrade>);
JEI.hideItem(<item:ironchest:copper_to_silver_chest_upgrade>);
JEI.hideItem(<item:ironchest:diamond_to_crystal_chest_upgrade>);
JEI.hideItem(<item:ironchest:diamond_to_obsidian_chest_upgrade>);
JEI.hideItem(<item:ironchest:gold_to_diamond_chest_upgrade>);
JEI.hideItem(<item:ironchest:iron_to_gold_chest_upgrade>);
JEI.hideItem(<item:ironchest:silver_to_gold_chest_upgrade>);
JEI.hideItem(<item:ironchest:wood_to_copper_chest_upgrade>);
JEI.hideItem(<item:ironchest:wood_to_iron_chest_upgrade>);
JEI.hideItem(<item:mekanism:block_charcoal>);
JEI.hideItem(<item:mekanism:crafting_formula>);
JEI.hideItem(<item:mekanism:creative_bin>);
JEI.hideItem(<item:mekanism:creative_chemical_tank>);
JEI.hideItem(<item:mekanism:creative_energy_cube>);
JEI.hideItem(<item:mekanism:creative_fluid_tank>);
JEI.hideItem(<item:mekanism:dictionary>);
JEI.hideItem(<item:mekanism:dust_gold>);
JEI.hideItem(<item:mekanism:dust_iron>);
JEI.hideItem(<item:mekanism:dust_quartz>);
JEI.hideItem(<item:mekanism:enriched_iron>);
JEI.hideItem(<item:mekanism:formulaic_assemblicator>);
JEI.hideItem(<item:mekanism:hdpe_rod>);
JEI.hideItem(<item:mekanism:hdpe_sheet>);
JEI.hideItem(<item:mekanism:nugget_lead>);
JEI.hideItem(<item:mekanism:nugget_osmium>);
JEI.hideItem(<item:mekanism:nugget_refined_glowstone>);
JEI.hideItem(<item:mekanism:nugget_refined_obsidian>);
JEI.hideItem(<item:mekanism:nugget_uranium>);
JEI.hideItem(<item:mekanism:oredictionificator>);
JEI.hideItem(<item:mekanism:portable_qio_dashboard>);
JEI.hideItem(<item:mekanism:qio_dashboard>);
JEI.hideItem(<item:mekanism:qio_drive_array>);
JEI.hideItem(<item:mekanism:qio_drive_base>);
JEI.hideItem(<item:mekanism:qio_drive_hyper_dense>);
JEI.hideItem(<item:mekanism:qio_drive_supermassive>);
JEI.hideItem(<item:mekanism:qio_drive_time_dilating>);
JEI.hideItem(<item:mekanism:qio_exporter>);
JEI.hideItem(<item:mekanism:qio_importer>);
JEI.hideItem(<item:mekanism:qio_redstone_adapter>);
JEI.hideItem(<item:mekanism:sawdust>);
JEI.hideItem(<item:mekanismadditions:baby_skeleton_spawn_egg>);
JEI.hideItem(<item:mekanismadditions:baby_stray_spawn_egg>);
JEI.hideItem(<item:mekanismadditions:baby_wither_skeleton_spawn_egg>);
JEI.hideItem(<item:mekanismadditions:walkie_talkie>);
JEI.hideItem(<item:mekanismtools:bronze_paxel>);
JEI.hideItem(<item:mekanismtools:diamond_paxel>);
JEI.hideItem(<item:mekanismtools:gold_paxel>);
JEI.hideItem(<item:mekanismtools:iron_paxel>);
JEI.hideItem(<item:mekanismtools:lapis_lazuli_paxel>);
JEI.hideItem(<item:mekanismtools:netherite_paxel>);
JEI.hideItem(<item:mekanismtools:osmium_paxel>);
JEI.hideItem(<item:mekanismtools:refined_glowstone_paxel>);
JEI.hideItem(<item:mekanismtools:refined_obsidian_paxel>);
JEI.hideItem(<item:mekanismtools:steel_paxel>);
JEI.hideItem(<item:mekanismtools:stone_paxel>);
JEI.hideItem(<item:mekanismtools:wood_paxel>);
JEI.hideItem(<item:metalbarrels:copper_to_crystal>);
JEI.hideItem(<item:metalbarrels:copper_to_diamond>);
JEI.hideItem(<item:metalbarrels:copper_to_gold>);
JEI.hideItem(<item:metalbarrels:copper_to_iron>);
JEI.hideItem(<item:metalbarrels:copper_to_obsidian>);
JEI.hideItem(<item:metalbarrels:copper_to_silver>);
JEI.hideItem(<item:metalbarrels:diamond_to_crystal>);
JEI.hideItem(<item:metalbarrels:diamond_to_obsidian>);
JEI.hideItem(<item:metalbarrels:gold_to_crystal>);
JEI.hideItem(<item:metalbarrels:gold_to_diamond>);
JEI.hideItem(<item:metalbarrels:gold_to_obsidian>);
JEI.hideItem(<item:metalbarrels:iron_to_crystal>);
JEI.hideItem(<item:metalbarrels:iron_to_diamond>);
JEI.hideItem(<item:metalbarrels:iron_to_gold>);
JEI.hideItem(<item:metalbarrels:iron_to_obsidian>);
JEI.hideItem(<item:metalbarrels:iron_to_silver>);
JEI.hideItem(<item:metalbarrels:silver_to_crystal>);
JEI.hideItem(<item:metalbarrels:silver_to_diamond>);
JEI.hideItem(<item:metalbarrels:silver_to_gold>);
JEI.hideItem(<item:metalbarrels:silver_to_obsidian>);
JEI.hideItem(<item:metalbarrels:wood_to_copper>);
JEI.hideItem(<item:metalbarrels:wood_to_crystal>);
JEI.hideItem(<item:metalbarrels:wood_to_diamond>);
JEI.hideItem(<item:metalbarrels:wood_to_gold>);
JEI.hideItem(<item:metalbarrels:wood_to_iron>);
JEI.hideItem(<item:metalbarrels:wood_to_netherite>);
JEI.hideItem(<item:metalbarrels:wood_to_obsidian>);
JEI.hideItem(<item:metalbarrels:wood_to_silver>);
JEI.hideItem(<item:minecraft:bedrock>);
JEI.hideItem(<item:minecraft:brewing_stand>);
JEI.hideItem(<item:minecraft:chain_command_block>);
JEI.hideItem(<item:minecraft:command_block>);
JEI.hideItem(<item:minecraft:command_block_minecart>);
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:blazing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:homing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:siphon" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:vigor" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "charm:aerial_affinity" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "charm:tinted" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cofh_core:holding" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:disarm" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:growth" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:magnet" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:quickshot" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:venom" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:angler" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:cavalier" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:displacement" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:excavating" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:exp_boost" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:fire_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:frost_aspect" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:frost_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:furrowing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:gourmand" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:hunter" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:leech" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:magic_edge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:magic_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:phalanx" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:quick_draw" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:reach" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:tilling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:trueshot" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:vitality" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:vorpal" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:blast_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:depth_strider" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:feather_falling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:fire_aspect" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:fire_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:fortune" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:frost_walker" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:knockback" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:looting" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:loyalty" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:luck_of_the_sea" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:lure" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:piercing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:projectile_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:punch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:quick_charge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:respiration" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:riptide" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:soul_speed" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:sweeping" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:thorns" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:unbreaking" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:homing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:hops" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:nimble" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:vigor" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cofh_core:holding" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:disarm" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:growth" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:magnet" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:quickshot" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:cavalier" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:displacement" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:exp_boost" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:fire_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:frost_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:furrowing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:leech" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:magic_edge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:magic_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:quick_draw" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:tilling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:vitality" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:vorpal" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:blast_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:depth_strider" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:feather_falling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:fire_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:fortune" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:looting" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:loyalty" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:luck_of_the_sea" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:lure" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:piercing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:projectile_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:quick_charge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:respiration" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:riptide" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:soul_speed" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:sweeping" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:thorns" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:unbreaking" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:homing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:hops" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:nimble" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:vigor" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "cofh_core:holding" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:furrowing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:leech" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:magic_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:tilling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:blast_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:feather_falling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:fire_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:piercing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:projectile_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 6 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 7 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 8 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 9 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:petrified_oak_slab>);
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:water" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:awkward" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:water" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:awkward" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:water" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:awkward" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:repeating_command_block>);
JEI.hideItem(<item:mysticalagriculture:air_agglomeratio>);
JEI.hideItem(<item:mysticalagriculture:basic_reprocessor>);
JEI.hideItem(<item:mysticalagriculture:earth_agglomeratio>);
JEI.hideItem(<item:mysticalagriculture:end_agglomeratio>);
JEI.hideItem(<item:mysticalagriculture:fire_agglomeratio>);
JEI.hideItem(<item:mysticalagriculture:imperium_gemstone>);
JEI.hideItem(<item:mysticalagriculture:imperium_gemstone_block>);
JEI.hideItem(<item:mysticalagriculture:imperium_nugget>);
JEI.hideItem(<item:mysticalagriculture:imperium_reprocessor>);
JEI.hideItem(<item:mysticalagriculture:imperium_staff>);
JEI.hideItem(<item:mysticalagriculture:inferium_gemstone>);
JEI.hideItem(<item:mysticalagriculture:inferium_gemstone_block>);
JEI.hideItem(<item:mysticalagriculture:inferium_nugget>);
JEI.hideItem(<item:mysticalagriculture:inferium_reprocessor>);
JEI.hideItem(<item:mysticalagriculture:inferium_staff>);
JEI.hideItem(<item:mysticalagriculture:infusion_crystal>);
JEI.hideItem(<item:mysticalagriculture:machine_frame>);
JEI.hideItem(<item:mysticalagriculture:master_infusion_crystal>);
JEI.hideItem(<item:mysticalagriculture:nether_agglomeratio>);
JEI.hideItem(<item:mysticalagriculture:prosperity_gemstone>);
JEI.hideItem(<item:mysticalagriculture:prosperity_gemstone_block>);
JEI.hideItem(<item:mysticalagriculture:prosperity_nugget>);
JEI.hideItem(<item:mysticalagriculture:prudentium_gemstone>);
JEI.hideItem(<item:mysticalagriculture:prudentium_gemstone_block>);
JEI.hideItem(<item:mysticalagriculture:prudentium_nugget>);
JEI.hideItem(<item:mysticalagriculture:prudentium_reprocessor>);
JEI.hideItem(<item:mysticalagriculture:prudentium_staff>);
JEI.hideItem(<item:mysticalagriculture:soul_dust>);
JEI.hideItem(<item:mysticalagriculture:soulium_gemstone>);
JEI.hideItem(<item:mysticalagriculture:soulium_gemstone_block>);
JEI.hideItem(<item:mysticalagriculture:soulium_nugget>);
JEI.hideItem(<item:mysticalagriculture:supremium_gemstone>);
JEI.hideItem(<item:mysticalagriculture:supremium_gemstone_block>);
JEI.hideItem(<item:mysticalagriculture:supremium_nugget>);
JEI.hideItem(<item:mysticalagriculture:supremium_reprocessor>);
JEI.hideItem(<item:mysticalagriculture:supremium_staff>);
JEI.hideItem(<item:mysticalagriculture:tertium_gemstone>);
JEI.hideItem(<item:mysticalagriculture:tertium_gemstone_block>);
JEI.hideItem(<item:mysticalagriculture:tertium_nugget>);
JEI.hideItem(<item:mysticalagriculture:tertium_reprocessor>);
JEI.hideItem(<item:mysticalagriculture:tertium_staff>);
JEI.hideItem(<item:mysticalagriculture:water_agglomeratio>);
JEI.hideItem(<item:patchouli:guide_book>.withTag({"patchouli:book": "cyclic:cyclic_guide_book" as string}));
JEI.hideItem(<item:patchouli:guide_book>.withTag({"patchouli:book": "industrialforegoing:industrial_foregoing" as string}));
JEI.hideItem(<item:patchouli:guide_book>.withTag({"patchouli:book": "mysticalagriculture:guide" as string}));
JEI.hideItem(<item:patchouli:guide_book>.withTag({"patchouli:book": "thermal:guidebook" as string}));
JEI.hideItem(<item:pickletweaks:diamond_scythe>);
JEI.hideItem(<item:pickletweaks:diamond_sickle>);
JEI.hideItem(<item:pickletweaks:emerald_scythe>);
JEI.hideItem(<item:pickletweaks:emerald_sickle>);
JEI.hideItem(<item:pickletweaks:flint_scythe>);
JEI.hideItem(<item:pickletweaks:flint_shears>);
JEI.hideItem(<item:pickletweaks:flint_sickle>);
JEI.hideItem(<item:pickletweaks:golden_scythe>);
JEI.hideItem(<item:pickletweaks:golden_sickle>);
JEI.hideItem(<item:pickletweaks:iron_scythe>);
JEI.hideItem(<item:pickletweaks:iron_sickle>);
JEI.hideItem(<item:pickletweaks:magnet>);
JEI.hideItem(<item:pickletweaks:netherite_scythe>);
JEI.hideItem(<item:pickletweaks:netherite_sickle>);
JEI.hideItem(<item:pickletweaks:reinforced_watering_can>);
JEI.hideItem(<item:pickletweaks:stone_scythe>);
JEI.hideItem(<item:pickletweaks:stone_sickle>);
JEI.hideItem(<item:pickletweaks:watering_can>);
JEI.hideItem(<item:pickletweaks:wooden_scythe>);
JEI.hideItem(<item:pickletweaks:wooden_sickle>);
JEI.hideItem(<item:quark:backpack>);
JEI.hideItem(<item:quark:bonded_ravager_hide>);
JEI.hideItem(<item:quark:charcoal_block>);
JEI.hideItem(<item:quark:chute>);
JEI.hideItem(<item:quark:crate>);
JEI.hideItem(<item:quark:ender_watcher>);
JEI.hideItem(<item:quark:feeding_trough>);
JEI.hideItem(<item:quark:obsidian_pressure_plate>);
JEI.hideItem(<item:quark:pipe>);
JEI.hideItem(<item:quark:ravager_hide>);
JEI.hideItem(<item:securitycraft:admin_tool>);
JEI.hideItem(<item:securitycraft:ancient_debris_mine>);
JEI.hideItem(<item:securitycraft:block_pocket_manager>);
JEI.hideItem(<item:securitycraft:block_pocket_wall>);
JEI.hideItem(<item:securitycraft:coal_mine>);
JEI.hideItem(<item:securitycraft:furnace_mine>);
JEI.hideItem(<item:securitycraft:quartz_mine>);
JEI.hideItem(<item:securitycraft:reinforced_andesite>);
JEI.hideItem(<item:securitycraft:reinforced_andesite_slab>);
JEI.hideItem(<item:securitycraft:reinforced_andesite_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_andesite_wall>);
JEI.hideItem(<item:securitycraft:reinforced_basalt>);
JEI.hideItem(<item:securitycraft:reinforced_blackstone>);
JEI.hideItem(<item:securitycraft:reinforced_blackstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_blackstone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_blackstone_wall>);
JEI.hideItem(<item:securitycraft:reinforced_blue_ice>);
JEI.hideItem(<item:securitycraft:reinforced_bone_block>);
JEI.hideItem(<item:securitycraft:reinforced_bookshelf>);
JEI.hideItem(<item:securitycraft:reinforced_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_brick_wall>);
JEI.hideItem(<item:securitycraft:reinforced_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_chain>);
JEI.hideItem(<item:securitycraft:reinforced_chiseled_crystal_quartz_block>);
JEI.hideItem(<item:securitycraft:reinforced_chiseled_nether_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_chiseled_polished_blackstone>);
JEI.hideItem(<item:securitycraft:reinforced_chiseled_quartz_block>);
JEI.hideItem(<item:securitycraft:reinforced_chiseled_red_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_chiseled_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_chiseled_stone_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_clay>);
JEI.hideItem(<item:securitycraft:reinforced_coal_block>);
JEI.hideItem(<item:securitycraft:reinforced_coarse_dirt>);
JEI.hideItem(<item:securitycraft:reinforced_cobblestone>);
JEI.hideItem(<item:securitycraft:reinforced_cobblestone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_cobblestone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_cobblestone_wall>);
JEI.hideItem(<item:securitycraft:reinforced_cobweb>);
JEI.hideItem(<item:securitycraft:reinforced_cracked_nether_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_cracked_polished_blackstone_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_cracked_stone_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_crying_obsidian>);
JEI.hideItem(<item:securitycraft:reinforced_crystal_quartz_block>);
JEI.hideItem(<item:securitycraft:reinforced_crystal_quartz_pillar>);
JEI.hideItem(<item:securitycraft:reinforced_crystal_quartz_slab>);
JEI.hideItem(<item:securitycraft:reinforced_crystal_quartz_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_cut_red_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_cut_red_sandstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_cut_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_cut_sandstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_dark_prismarine>);
JEI.hideItem(<item:securitycraft:reinforced_dark_prismarine_slab>);
JEI.hideItem(<item:securitycraft:reinforced_dark_prismarine_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_diamond_block>);
JEI.hideItem(<item:securitycraft:reinforced_diorite>);
JEI.hideItem(<item:securitycraft:reinforced_diorite_slab>);
JEI.hideItem(<item:securitycraft:reinforced_diorite_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_diorite_wall>);
JEI.hideItem(<item:securitycraft:reinforced_dirt>);
JEI.hideItem(<item:securitycraft:reinforced_emerald_block>);
JEI.hideItem(<item:securitycraft:reinforced_end_stone>);
JEI.hideItem(<item:securitycraft:reinforced_end_stone_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_end_stone_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_end_stone_brick_wall>);
JEI.hideItem(<item:securitycraft:reinforced_end_stone_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_glass>);
JEI.hideItem(<item:securitycraft:reinforced_glass_pane>);
JEI.hideItem(<item:securitycraft:reinforced_glowstone>);
JEI.hideItem(<item:securitycraft:reinforced_gold_block>);
JEI.hideItem(<item:securitycraft:reinforced_granite>);
JEI.hideItem(<item:securitycraft:reinforced_granite_slab>);
JEI.hideItem(<item:securitycraft:reinforced_granite_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_granite_wall>);
JEI.hideItem(<item:securitycraft:reinforced_grass_block>);
JEI.hideItem(<item:securitycraft:reinforced_grass_path>);
JEI.hideItem(<item:securitycraft:reinforced_gravel>);
JEI.hideItem(<item:securitycraft:reinforced_hardened_clay>);
JEI.hideItem(<item:securitycraft:reinforced_hopper>);
JEI.hideItem(<item:securitycraft:reinforced_ice>);
JEI.hideItem(<item:securitycraft:reinforced_iron_block>);
JEI.hideItem(<item:securitycraft:reinforced_lantern>);
JEI.hideItem(<item:securitycraft:reinforced_lapis_block>);
JEI.hideItem(<item:securitycraft:reinforced_lever>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_cobblestone>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_cobblestone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_cobblestone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_cobblestone_wall>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_stone_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_stone_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_stone_brick_wall>);
JEI.hideItem(<item:securitycraft:reinforced_mossy_stone_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_mycelium>);
JEI.hideItem(<item:securitycraft:reinforced_nether_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_nether_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_nether_brick_wall>);
JEI.hideItem(<item:securitycraft:reinforced_nether_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_nether_wart_block>);
JEI.hideItem(<item:securitycraft:reinforced_netherite_block>);
JEI.hideItem(<item:securitycraft:reinforced_netherrack>);
JEI.hideItem(<item:securitycraft:reinforced_normal_stone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_observer>);
JEI.hideItem(<item:securitycraft:reinforced_obsidian>);
JEI.hideItem(<item:securitycraft:reinforced_packed_ice>);
JEI.hideItem(<item:securitycraft:reinforced_podzol>);
JEI.hideItem(<item:securitycraft:reinforced_polished_andesite>);
JEI.hideItem(<item:securitycraft:reinforced_polished_andesite_slab>);
JEI.hideItem(<item:securitycraft:reinforced_polished_andesite_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_polished_basalt>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_brick_wall>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_button>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_pressure_plate>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_polished_blackstone_wall>);
JEI.hideItem(<item:securitycraft:reinforced_polished_diorite>);
JEI.hideItem(<item:securitycraft:reinforced_polished_diorite_slab>);
JEI.hideItem(<item:securitycraft:reinforced_polished_diorite_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_polished_granite>);
JEI.hideItem(<item:securitycraft:reinforced_polished_granite_slab>);
JEI.hideItem(<item:securitycraft:reinforced_polished_granite_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_prismarine>);
JEI.hideItem(<item:securitycraft:reinforced_prismarine_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_prismarine_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_prismarine_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_prismarine_slab>);
JEI.hideItem(<item:securitycraft:reinforced_prismarine_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_prismarine_wall>);
JEI.hideItem(<item:securitycraft:reinforced_purpur_block>);
JEI.hideItem(<item:securitycraft:reinforced_purpur_pillar>);
JEI.hideItem(<item:securitycraft:reinforced_purpur_slab>);
JEI.hideItem(<item:securitycraft:reinforced_purpur_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_quartz_block>);
JEI.hideItem(<item:securitycraft:reinforced_quartz_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_quartz_pillar>);
JEI.hideItem(<item:securitycraft:reinforced_quartz_slab>);
JEI.hideItem(<item:securitycraft:reinforced_quartz_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_red_nether_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_red_nether_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_red_nether_brick_wall>);
JEI.hideItem(<item:securitycraft:reinforced_red_nether_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_red_sand>);
JEI.hideItem(<item:securitycraft:reinforced_red_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_red_sandstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_red_sandstone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_red_sandstone_wall>);
JEI.hideItem(<item:securitycraft:reinforced_redstone_block>);
JEI.hideItem(<item:securitycraft:reinforced_redstone_lamp>);
JEI.hideItem(<item:securitycraft:reinforced_sand>);
JEI.hideItem(<item:securitycraft:reinforced_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_sandstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_sandstone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_sandstone_wall>);
JEI.hideItem(<item:securitycraft:reinforced_sea_lantern>);
JEI.hideItem(<item:securitycraft:reinforced_shroomlight>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_quartz>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_quartz_slab>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_quartz_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_red_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_red_sandstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_red_sandstone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_sandstone>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_sandstone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_sandstone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_smooth_stone>);
JEI.hideItem(<item:securitycraft:reinforced_snow_block>);
JEI.hideItem(<item:securitycraft:reinforced_soul_lantern>);
JEI.hideItem(<item:securitycraft:reinforced_soul_soil>);
JEI.hideItem(<item:securitycraft:reinforced_stone>);
JEI.hideItem(<item:securitycraft:reinforced_stone_brick_slab>);
JEI.hideItem(<item:securitycraft:reinforced_stone_brick_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_stone_brick_wall>);
JEI.hideItem(<item:securitycraft:reinforced_stone_bricks>);
JEI.hideItem(<item:securitycraft:reinforced_stone_button>);
JEI.hideItem(<item:securitycraft:reinforced_stone_pressure_plate>);
JEI.hideItem(<item:securitycraft:reinforced_stone_slab>);
JEI.hideItem(<item:securitycraft:reinforced_stone_stairs>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_acacia_log>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_acacia_wood>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_birch_log>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_birch_wood>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_crimson_hyphae>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_crimson_stem>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_dark_oak_log>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_dark_oak_wood>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_jungle_log>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_jungle_wood>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_oak_log>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_oak_wood>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_spruce_log>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_spruce_wood>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_warped_hyphae>);
JEI.hideItem(<item:securitycraft:reinforced_stripped_warped_stem>);
JEI.hideItem(<item:securitycraft:reinforced_warped_wart_block>);
JEI.hideItem(<item:securitycraft:sand_mine>);
JEI.hideItem(<item:securitycraft:sc_manual>);
JEI.hideItem(<item:securitycraft:track_mine>);
JEI.hideItem(<item:securitycraft:universal_block_reinforcer_lvl1>);
JEI.hideItem(<item:securitycraft:universal_block_reinforcer_lvl2>);
JEI.hideItem(<item:securitycraft:universal_block_reinforcer_lvl3>);
JEI.hideItem(<item:theoneprobe:creativeprobe>);
JEI.hideItem(<item:theoneprobe:diamond_helmet_probe>);
JEI.hideItem(<item:theoneprobe:gold_helmet_probe>);
JEI.hideItem(<item:theoneprobe:iron_helmet_probe>);
JEI.hideItem(<item:theoneprobe:probe>);
JEI.hideItem(<item:theoneprobe:probenote>);
JEI.hideItem(<item:thermal:apatite>);
JEI.hideItem(<item:thermal:apatite_block>);
JEI.hideItem(<item:thermal:apatite_dust>);
JEI.hideItem(<item:thermal:apatite_ore>);
JEI.hideItem(<item:thermal:area_radius_augment>);
JEI.hideItem(<item:thermal:bronze_block>);
JEI.hideItem(<item:thermal:bronze_coin>);
JEI.hideItem(<item:thermal:bronze_dust>);
JEI.hideItem(<item:thermal:bronze_gear>);
JEI.hideItem(<item:thermal:bronze_ingot>);
JEI.hideItem(<item:thermal:bronze_nugget>);
JEI.hideItem(<item:thermal:bronze_plate>);
JEI.hideItem(<item:thermal:chiller_ball_cast>);
JEI.hideItem(<item:thermal:chiller_ingot_cast>);
JEI.hideItem(<item:thermal:chiller_rod_cast>);
JEI.hideItem(<item:thermal:cinnabar>);
JEI.hideItem(<item:thermal:cinnabar_block>);
JEI.hideItem(<item:thermal:cinnabar_dust>);
JEI.hideItem(<item:thermal:cinnabar_ore>);
JEI.hideItem(<item:thermal:constantan_block>);
JEI.hideItem(<item:thermal:constantan_coin>);
JEI.hideItem(<item:thermal:constantan_dust>);
JEI.hideItem(<item:thermal:constantan_gear>);
JEI.hideItem(<item:thermal:constantan_ingot>);
JEI.hideItem(<item:thermal:constantan_nugget>);
JEI.hideItem(<item:thermal:constantan_plate>);
JEI.hideItem(<item:thermal:copper_block>);
JEI.hideItem(<item:thermal:copper_coin>);
JEI.hideItem(<item:thermal:copper_dust>);
JEI.hideItem(<item:thermal:copper_gear>);
JEI.hideItem(<item:thermal:copper_ingot>);
JEI.hideItem(<item:thermal:copper_nugget>);
JEI.hideItem(<item:thermal:copper_ore>);
JEI.hideItem(<item:thermal:copper_plate>);
JEI.hideItem(<item:thermal:creosote_bucket>);
JEI.hideItem(<item:thermal:crude_oil_bucket>);
JEI.hideItem(<item:thermal:cured_rubber>);
JEI.hideItem(<item:thermal:cured_rubber_block>);
JEI.hideItem(<item:thermal:device_collector>);
JEI.hideItem(<item:thermal:device_nullifier>);
JEI.hideItem(<item:thermal:device_rock_gen>);
JEI.hideItem(<item:thermal:device_tree_extractor>);
JEI.hideItem(<item:thermal:device_water_gen>);
JEI.hideItem(<item:thermal:diamond_dust>);
JEI.hideItem(<item:thermal:diamond_gear>);
JEI.hideItem(<item:thermal:drill_head>);
JEI.hideItem(<item:thermal:dynamo_compression>);
JEI.hideItem(<item:thermal:dynamo_fuel_augment>);
JEI.hideItem(<item:thermal:dynamo_lapidary>);
JEI.hideItem(<item:thermal:dynamo_magmatic>);
JEI.hideItem(<item:thermal:dynamo_numismatic>);
JEI.hideItem(<item:thermal:dynamo_output_augment>);
JEI.hideItem(<item:thermal:dynamo_stirling>);
JEI.hideItem(<item:thermal:electrum_block>);
JEI.hideItem(<item:thermal:electrum_coin>);
JEI.hideItem(<item:thermal:electrum_dust>);
JEI.hideItem(<item:thermal:electrum_gear>);
JEI.hideItem(<item:thermal:electrum_ingot>);
JEI.hideItem(<item:thermal:electrum_nugget>);
JEI.hideItem(<item:thermal:electrum_plate>);
JEI.hideItem(<item:thermal:emerald_dust>);
JEI.hideItem(<item:thermal:emerald_gear>);
JEI.hideItem(<item:thermal:ender_pearl_dust>);
JEI.hideItem(<item:thermal:enderium_block>);
JEI.hideItem(<item:thermal:enderium_coin>);
JEI.hideItem(<item:thermal:enderium_dust>);
JEI.hideItem(<item:thermal:enderium_gear>);
JEI.hideItem(<item:thermal:enderium_glass>);
JEI.hideItem(<item:thermal:enderium_ingot>);
JEI.hideItem(<item:thermal:enderium_nugget>);
JEI.hideItem(<item:thermal:enderium_plate>);
JEI.hideItem(<item:thermal:energy_cell>);
JEI.hideItem(<item:thermal:energy_cell_frame>);
JEI.hideItem(<item:thermal:fluid_cell>);
JEI.hideItem(<item:thermal:fluid_cell_frame>);
JEI.hideItem(<item:thermal:fluid_tank_augment>);
JEI.hideItem(<item:thermal:fluid_tank_creative_augment>);
JEI.hideItem(<item:thermal:gold_coin>);
JEI.hideItem(<item:thermal:gold_dust>);
JEI.hideItem(<item:thermal:gold_gear>);
JEI.hideItem(<item:thermal:gold_plate>);
JEI.hideItem(<item:thermal:heavy_oil_bucket>);
JEI.hideItem(<item:thermal:invar_block>);
JEI.hideItem(<item:thermal:invar_coin>);
JEI.hideItem(<item:thermal:invar_dust>);
JEI.hideItem(<item:thermal:invar_gear>);
JEI.hideItem(<item:thermal:invar_ingot>);
JEI.hideItem(<item:thermal:invar_nugget>);
JEI.hideItem(<item:thermal:invar_plate>);
JEI.hideItem(<item:thermal:iron_coin>);
JEI.hideItem(<item:thermal:iron_dust>);
JEI.hideItem(<item:thermal:iron_gear>);
JEI.hideItem(<item:thermal:iron_plate>);
JEI.hideItem(<item:thermal:item_filter_augment>);
JEI.hideItem(<item:thermal:lapis_dust>);
JEI.hideItem(<item:thermal:lapis_gear>);
JEI.hideItem(<item:thermal:latex_bucket>);
JEI.hideItem(<item:thermal:lead_block>);
JEI.hideItem(<item:thermal:lead_coin>);
JEI.hideItem(<item:thermal:lead_dust>);
JEI.hideItem(<item:thermal:lead_gear>);
JEI.hideItem(<item:thermal:lead_ingot>);
JEI.hideItem(<item:thermal:lead_nugget>);
JEI.hideItem(<item:thermal:lead_ore>);
JEI.hideItem(<item:thermal:lead_plate>);
JEI.hideItem(<item:thermal:light_oil_bucket>);
JEI.hideItem(<item:thermal:lock>);
JEI.hideItem(<item:thermal:lumium_block>);
JEI.hideItem(<item:thermal:lumium_coin>);
JEI.hideItem(<item:thermal:lumium_dust>);
JEI.hideItem(<item:thermal:lumium_gear>);
JEI.hideItem(<item:thermal:lumium_glass>);
JEI.hideItem(<item:thermal:lumium_ingot>);
JEI.hideItem(<item:thermal:lumium_nugget>);
JEI.hideItem(<item:thermal:lumium_plate>);
JEI.hideItem(<item:thermal:machine_bottler>);
JEI.hideItem(<item:thermal:machine_brewer>);
JEI.hideItem(<item:thermal:machine_catalyst_augment>);
JEI.hideItem(<item:thermal:machine_catalyst_creative_augment>);
JEI.hideItem(<item:thermal:machine_centrifuge>);
JEI.hideItem(<item:thermal:machine_chiller>);
JEI.hideItem(<item:thermal:machine_crafter>);
JEI.hideItem(<item:thermal:machine_crucible>);
JEI.hideItem(<item:thermal:machine_cycle_augment>);
JEI.hideItem(<item:thermal:machine_efficiency_augment>);
JEI.hideItem(<item:thermal:machine_efficiency_creative_augment>);
JEI.hideItem(<item:thermal:machine_frame>);
JEI.hideItem(<item:thermal:machine_furnace>);
JEI.hideItem(<item:thermal:machine_insolator>);
JEI.hideItem(<item:thermal:machine_output_augment>);
JEI.hideItem(<item:thermal:machine_press>);
JEI.hideItem(<item:thermal:machine_pulverizer>);
JEI.hideItem(<item:thermal:machine_pyrolyzer>);
JEI.hideItem(<item:thermal:machine_refinery>);
JEI.hideItem(<item:thermal:machine_sawmill>);
JEI.hideItem(<item:thermal:machine_smelter>);
JEI.hideItem(<item:thermal:machine_speed_augment>);
JEI.hideItem(<item:thermal:nickel_block>);
JEI.hideItem(<item:thermal:nickel_coin>);
JEI.hideItem(<item:thermal:nickel_dust>);
JEI.hideItem(<item:thermal:nickel_gear>);
JEI.hideItem(<item:thermal:nickel_ingot>);
JEI.hideItem(<item:thermal:nickel_nugget>);
JEI.hideItem(<item:thermal:nickel_ore>);
JEI.hideItem(<item:thermal:nickel_plate>);
JEI.hideItem(<item:thermal:niter>);
JEI.hideItem(<item:thermal:niter_block>);
JEI.hideItem(<item:thermal:niter_dust>);
JEI.hideItem(<item:thermal:niter_ore>);
JEI.hideItem(<item:thermal:phytogro>);
JEI.hideItem(<item:thermal:press_coin_die>);
JEI.hideItem(<item:thermal:press_gear_die>);
JEI.hideItem(<item:thermal:press_packing_2x2_die>);
JEI.hideItem(<item:thermal:press_packing_3x3_die>);
JEI.hideItem(<item:thermal:press_unpacking_die>);
JEI.hideItem(<item:thermal:quartz_dust>);
JEI.hideItem(<item:thermal:quartz_gear>);
JEI.hideItem(<item:thermal:redprint>);
JEI.hideItem(<item:thermal:redstone_servo>);
JEI.hideItem(<item:thermal:refined_fuel_bucket>);
JEI.hideItem(<item:thermal:resin_bucket>);
JEI.hideItem(<item:thermal:rf_coil>);
JEI.hideItem(<item:thermal:rf_coil_augment>);
JEI.hideItem(<item:thermal:rf_coil_creative_augment>);
JEI.hideItem(<item:thermal:rf_coil_storage_augment>);
JEI.hideItem(<item:thermal:rf_coil_xfer_augment>);
JEI.hideItem(<item:thermal:rich_slag>);
JEI.hideItem(<item:thermal:rich_slag_block>);
JEI.hideItem(<item:thermal:rosin>);
JEI.hideItem(<item:thermal:rosin_block>);
JEI.hideItem(<item:thermal:rubber>);
JEI.hideItem(<item:thermal:rubber_block>);
JEI.hideItem(<item:thermal:sap_bucket>);
JEI.hideItem(<item:thermal:signalum_block>);
JEI.hideItem(<item:thermal:signalum_coin>);
JEI.hideItem(<item:thermal:signalum_dust>);
JEI.hideItem(<item:thermal:signalum_gear>);
JEI.hideItem(<item:thermal:signalum_glass>);
JEI.hideItem(<item:thermal:signalum_ingot>);
JEI.hideItem(<item:thermal:signalum_nugget>);
JEI.hideItem(<item:thermal:signalum_plate>);
JEI.hideItem(<item:thermal:silver_block>);
JEI.hideItem(<item:thermal:silver_coin>);
JEI.hideItem(<item:thermal:silver_dust>);
JEI.hideItem(<item:thermal:silver_gear>);
JEI.hideItem(<item:thermal:silver_ingot>);
JEI.hideItem(<item:thermal:silver_nugget>);
JEI.hideItem(<item:thermal:silver_ore>);
JEI.hideItem(<item:thermal:silver_plate>);
JEI.hideItem(<item:thermal:slag>);
JEI.hideItem(<item:thermal:slag_block>);
JEI.hideItem(<item:thermal:sulfur>);
JEI.hideItem(<item:thermal:sulfur_block>);
JEI.hideItem(<item:thermal:sulfur_dust>);
JEI.hideItem(<item:thermal:sulfur_ore>);
JEI.hideItem(<item:thermal:syrup_bucket>);
JEI.hideItem(<item:thermal:tin_block>);
JEI.hideItem(<item:thermal:tin_coin>);
JEI.hideItem(<item:thermal:tin_dust>);
JEI.hideItem(<item:thermal:tin_gear>);
JEI.hideItem(<item:thermal:tin_ingot>);
JEI.hideItem(<item:thermal:tin_nugget>);
JEI.hideItem(<item:thermal:tin_ore>);
JEI.hideItem(<item:thermal:tin_plate>);
JEI.hideItem(<item:thermal:tinker_bench>);
JEI.hideItem(<item:thermal:tree_oil_bucket>);
JEI.hideItem(<item:thermal:upgrade_augment_1>);
JEI.hideItem(<item:thermal:upgrade_augment_2>);
JEI.hideItem(<item:thermal:upgrade_augment_3>);
JEI.hideItem(<item:thermal:xp_crystal>);
JEI.hideItem(<item:thermal:xp_storage_augment>);
JEI.hideItem(<item:titanium:diamond_gear>);
JEI.hideItem(<item:titanium:gold_gear>);
JEI.hideItem(<item:titanium:iron_gear>);
JEI.hideItem(<item:vanillatweaks:dynamite>);
JEI.hideItem(<item:vanillatweaks:pad>);
JEI.hideItem(<item:vanillatweaks:pedestal>);
JEI.hideItem(<item:vanillatweaks:slime>);
JEI.hideItem(<item:vanillatweaks:sugarblock>);