#priority 2
import mods.jei.JEI;
JEI.hideCategory("botania:orechid");
JEI.hideCategory("botania:orechid_ignem");
JEI.hideCategory("botania:terra_plate");
JEI.hideCategory("cookingforblockheads:cow_jar");
JEI.hideCategory("industrialforegoing:bioreactor");
JEI.hideCategory("industrialforegoing:machine_produce");
JEI.hideCategory("industrialforegoing:mycelial_crimed");
JEI.hideCategory("industrialforegoing:mycelial_culinary");
JEI.hideCategory("industrialforegoing:mycelial_death");
JEI.hideCategory("industrialforegoing:mycelial_disenchantment");
JEI.hideCategory("industrialforegoing:mycelial_ender");
JEI.hideCategory("industrialforegoing:mycelial_explosive");
JEI.hideCategory("industrialforegoing:mycelial_frosty");
JEI.hideCategory("industrialforegoing:mycelial_furnace");
JEI.hideCategory("industrialforegoing:mycelial_halitosis");
JEI.hideCategory("industrialforegoing:mycelial_magma");
JEI.hideCategory("industrialforegoing:mycelial_meatallurgic");
JEI.hideCategory("industrialforegoing:mycelial_netherstar");
JEI.hideCategory("industrialforegoing:mycelial_pink");
JEI.hideCategory("industrialforegoing:mycelial_potion");
JEI.hideCategory("industrialforegoing:mycelial_slimey");
JEI.hideCategory("industrialforegoing:ore_fermenter");
JEI.hideCategory("industrialforegoing:ore_sieve");
JEI.hideCategory("industrialforegoing:ore_washer");
JEI.hideCategory("jei:information");
JEI.hideCategory("mekanism:energized_smelter");
JEI.hideCategory("minecraft:anvil");
JEI.hideCategory("minecraft:brewing");
JEI.hideCategory("securitycraft:securitycraft_to_vanilla");
JEI.hideCategory("securitycraft:vanilla_to_securitycraft");
JEI.hideItem(<item:appliedenergistics2:certus_crystal_seed>);
JEI.hideItem(<item:appliedenergistics2:nether_quartz_seed>);
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:blazing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:homing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:siphon" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 0 as short, id: "vanillatweaks:vigor" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "charm:aerial_affinity" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "charm:tinted" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cofh_core:holding" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:disarm" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:growth" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:magnet" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:quickshot" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "cyclic:venom" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:angler" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:cavalier" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:displacement" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:excavating" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:exp_boost" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:fire_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:frost_aspect" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:frost_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:furrowing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:gourmand" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:hunter" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:leech" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:magic_edge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:magic_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:phalanx" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:quick_draw" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:reach" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:tilling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:trueshot" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:vitality" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "ensorcellation:vorpal" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:blast_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:depth_strider" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:feather_falling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:fire_aspect" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:fire_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:fortune" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:frost_walker" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:knockback" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:looting" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:loyalty" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:luck_of_the_sea" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:lure" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:piercing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:projectile_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:punch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:quick_charge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:respiration" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:riptide" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:soul_speed" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:sweeping" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:thorns" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "minecraft:unbreaking" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:homing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:hops" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:nimble" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: "vanillatweaks:vigor" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cofh_core:holding" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:disarm" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:growth" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:magnet" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "cyclic:quickshot" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:cavalier" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:displacement" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:exp_boost" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:fire_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:frost_rebuke" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:furrowing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:leech" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:magic_edge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:magic_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:quick_draw" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:tilling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:vitality" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "ensorcellation:vorpal" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:blast_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:depth_strider" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:feather_falling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:fire_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:fortune" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:looting" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:loyalty" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:luck_of_the_sea" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:lure" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:piercing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:projectile_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:quick_charge" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:respiration" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:riptide" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:soul_speed" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:sweeping" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:thorns" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "minecraft:unbreaking" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:homing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:hops" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:nimble" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: "vanillatweaks:vigor" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "cofh_core:holding" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:furrowing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:leech" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:magic_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "ensorcellation:tilling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:blast_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:feather_falling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:fire_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:piercing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:projectile_protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:protection" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "apotheosis:capturing" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "ensorcellation:damage_ender" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "ensorcellation:damage_illager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "ensorcellation:damage_villager" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:bane_of_arthropods" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:efficiency" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:impaling" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:power" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:sharpness" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: "minecraft:smite" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 6 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 7 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 8 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 9 as short, id: "cyclic:launch" as string}]}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:awkward" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:water" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:lingering_potion>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:potion>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:awkward" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:water" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:splash_potion>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:haste" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:strong_haste" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:stun" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "cyclic:swimspeed" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:awkward" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:fire_resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:invisibility" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:leaping" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_leaping" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_poison" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_regeneration" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_slow_falling" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_turtle_master" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:luck" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:mundane" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:night_vision" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:poison" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:regeneration" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:slow_falling" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:slowness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strength" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_harming" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_healing" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_leaping" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_poison" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_regeneration" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_slowness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_strength" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_swiftness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_turtle_master" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:swiftness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:thick" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:turtle_master" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:water" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:water_breathing" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "minecraft:weakness" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:danger_sight" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:long_danger_sight" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:long_resilience" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:long_resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:resilience" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:resistance" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:strong_resilience" as string}));
JEI.hideItem(<item:minecraft:tipped_arrow>.withTag({Potion: "quark:strong_resistance" as string}));
JEI.hideItem(<item:mysticalagriculture:attack_aoe_i_augment>);
JEI.hideItem(<item:mysticalagriculture:attack_aoe_ii_augment>);
JEI.hideItem(<item:mysticalagriculture:attack_aoe_iii_augment>);
JEI.hideItem(<item:mysticalagriculture:strength_i_augment>);
JEI.hideItem(<item:mysticalagriculture:strength_ii_augment>);
JEI.hideItem(<item:mysticalagriculture:strength_iii_augment>);
JEI.hideItem(<item:mysticalagriculture:mining_aoe_i_augment>);
JEI.hideItem(<item:mysticalagriculture:mining_aoe_ii_augment>);
JEI.hideItem(<item:mysticalagriculture:mining_aoe_iii_augment>);
JEI.hideItem(<item:mysticalagriculture:mining_aoe_iv_augment>);
JEI.hideItem(<item:mysticalagriculture:pathing_aoe_i_augment>);
JEI.hideItem(<item:mysticalagriculture:pathing_aoe_ii_augment>);
JEI.hideItem(<item:mysticalagriculture:pathing_aoe_iii_augment>);
JEI.hideItem(<item:mysticalagriculture:pathing_aoe_iv_augment>);
JEI.hideItem(<item:mysticalagriculture:tilling_aoe_i_augment>);
JEI.hideItem(<item:mysticalagriculture:tilling_aoe_ii_augment>);
JEI.hideItem(<item:mysticalagriculture:tilling_aoe_iii_augment>);
JEI.hideItem(<item:mysticalagriculture:tilling_aoe_iv_augment>);
JEI.hideItem(<item:patchouli:guide_book>.withTag({"patchouli:book": "cyclic:cyclic_guide_book" as string}));
JEI.hideItem(<item:patchouli:guide_book>.withTag({"patchouli:book": "industrialforegoing:industrial_foregoing" as string}));
JEI.hideItem(<item:patchouli:guide_book>.withTag({"patchouli:book": "mysticalagriculture:guide" as string}));
